### ISSUE TITLE
Deploy JavaScript on build

### ISSUE THREAD

**Issue by chad-autry** [ronzeidman/ng2-ui-auth#1]
First of all, thanks for sharing your conversion. I expect it to be useful to many others.

For it to be widely adopted the compiled JavaScript needs to be published, since TypeScript is not a requirement for working with Angular2.

I'd recommend [TravisCI](https://travis-ci.org/) for the build, calling into a script in the package.json, and then pushing to npm. Optionally pushing back into github as well.

**Comment by chad-autry** [comment]
I'll get a pull request open with the repository files created that should do the above. It will take some further setup in TravisCI to get the auto build working there, and get the deploy pushing into npm.

**Comment by ronzeidman** [comment]
Thanks!
First time I hear about TravisCI, looks good.
Done, I've merged the pull request, committed transpiled files to github, added to npm, and compiled with TravisCI

**Comment by ronzeidman** [comment]
Auto-publish from Travis worked! took me a while though to find out that the npm api token is just my "user:password" encoded in base64... They really should make it more obvious.
