### ISSUE TITLE
No error but not working

### ISSUE THREAD

**Issue by tagazok** [ronzeidman/ng2-ui-auth#10]
Hi,
I am using angular2.beta2 with this yeoman generator : https://github.com/dsebastien/modernWebDevGenerator

Then, I just add the import
`import {JwtHttp} from "ng2-ui-auth";`

From this point, without any other modification to the bootstrap app, I get this error in my js console:
`GET http://localhost:3000/core/boot.js 404 (Not Found)fetchTextFromURL @ system.src.js:1068(anonymous function) @ system.src.js:1649lib$es6$promise$$internal$$initializePromise @ angular2-polyfills.js:1558lib$es6$promise$promise$$Promise @ angular2-polyfills.js:1849(anonymous function) @ system.src.js:1648(anonymous function) @ system.src.js:2670(anonymous function) @ system.src.js:3234(anonymous function) @ system.src.js:3501(anonymous function) @ system.src.js:4117(anonymous function) @ system.src.js:4325(anonymous function) @ system.src.js:4565(anonymous function) @ system.src.js:326run @ angular2-polyfills.js:138zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494(anonymous function) @ angular2-polyfills.js:243run @ angular2-polyfills.js:138zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305
angular2-polyfills.js:138 Error: XHR error (404 Not Found) loading http://localhost:3000/core/boot.js(…)`

I don't have any error in my npm console. It looks like that when I add the import, something goes wrong and my app doesn't even start (as it does not find boot.js for some reason)
Any idea where this comes from?

**Comment by ronzeidman** [comment]
try providing JwtHttp as follows:
```typescript
provide(JwtHttp, {
        useFactory:
            (xhrBackend, requestOptions, shared, config, router) =>
                new JwtHttp(xhrBackend, requestOptions, shared, config),
        deps: [XHRBackend, RequestOptions, Shared, Config],
    })
```

**Comment by tagazok** [comment]
Not working :(

Would you have a starter project that I can use?

**Comment by ronzeidman** [comment]
I'll try to cook something up, in the meanwhile, what's your config,js file looks like?

**Comment by tagazok** [comment]
ahah !
Maybe that's where the problem comes from and I am missing something :)
I don't have any config.js file

What should be in this file?

**Comment by ronzeidman** [comment]
try something like this:
```ts
SystemJS.config({
    defaultJSExtensions: true,
    paths: {
        '../*': '../*',
        './*': './*',
        '*': './node_modules/*'
    },
    packageConfigPaths: ['./node_modules/*/package.json'],
    map: {
        'crypto': "@empty"
    }
});
```

**Comment by tagazok** [comment]
Oh, this is in my jspm.conf.js actually.
I added the paths but it does not work.
Also, when I add the packageConfigPath, I have an error as I have some packages without package.json
`GET http://localhost:3000/node_modules/core/package.json 404 (Not Found)`

**Comment by ronzeidman** [comment]
Ohh, you're using jspm. I have a working project on jspm that doesn't seem to have an issue (although I've overridden the JwtHttp and provided a local implementation).
I'll try to make a small test project and share with you

**Comment by tagazok** [comment]
ok thanks :)
I am looking forward to seeing your test project.

**Comment by ronzeidman** [comment]
You should provide the JwtHttp as I mentioned.
I've created an example: https://github.com/ronzeidman/ng2-ui-auth-example
turned out to be a bit more complex then I've anticipated since it required both client and server to fully work.
anyway if you get a "reflet-metadata" error, try overriding it with: { map: { crypto: '@empty' }, format: 'global' } }
should work.
And as  every developer say "It works on my machine!"

**Comment by ronzeidman** [comment]
Try using the new version (1.1.0) and provide the JwtHttp using the JWT_HTTP_PROVIDER instead of the JwtHttp directly.
I've also updated the example accordingly.
