### ISSUE TITLE
ES2015 export

### ISSUE THREAD

**Issue by pcdummy** [ronzeidman/ng2-ui-auth#105]
Hi,

today I got this working [@pcdummy/angular-aot-es2015-rollup](https://github.com/pcdummy/angular-aot-es2015-rollup), its Angular 4.x with Tree-shaking (remove unneeded deps from the output).

This needs an ES2015 export in package.json (and ofc. the build of the files in releases) which is very good documented [here](https://github.com/robisim74/angular-library-starter).

Is there any interest in getting ES2015 exports into this library? If so i would make this happen with a PR.

**Comment by pcdummy** [comment]
A note: with tree-shaking Angular 4 compiles down to **355KiB**

**Comment by ronzeidman** [comment]
I'd be happy to get a PR.
Thanks!

**Comment by aitboudad** [comment]
That's something I've already done on my side see [@ui-auth/core](https://github.com/aitboudad/ng-gcc-build/tree/%40ui-auth/core/%40ui-auth) which follow [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview)

**Comment by aitboudad** [comment]
I'll try to provide a PR once I have time but not soon :), https://github.com/dherges/ng-packagr may help

**Comment by pcdummy** [comment]
@aitboudad thanks for the tip on ng-packagr its great!

@ronzeidman Pull request is there.

**Comment by ronzeidman** [comment]
Thanks, didn't know about ng-packager!

**Comment by aitboudad** [comment]
Note: `npm publish` should be executed inside `dist` folder

**Comment by pcdummy** [comment]
travis will do that.
