### ISSUE TITLE
not working for new HttpClient request from angular 4.3.0

### ISSUE THREAD

**Issue by shengnan1987** [ronzeidman/ng2-ui-auth#111]

**Comment by ronzeidman** [comment]
An interceptor should be added.

**Comment by aliasbody** [comment]
@ronzeidman I have the same issue, do you have any example code?

**Comment by gizbo** [comment]
I'm also interested in this.

**Comment by ronzeidman** [comment]
Try `npm i ng2-ui-auth@8.0.0-beta.2`. Works with HttpClient (angular >5.0.0).

**Comment by ronzeidman** [comment]
Look at the changelog for details

**Comment by ronzeidman** [comment]
version 8.0.0 works with angular 5,
