### ISSUE TITLE
Problem authenticating with facebook

### ISSUE THREAD

**Issue by mscoobby** [ronzeidman/ng2-ui-auth#113]
I'm trying to implement authentication with Facebook but got a weird error.
```
XMLHttpRequest cannot load https://www.facebook.com/dialog/oauth?response_type=code&redirect_uri=http%…facebook%2Fcallback&scope=email%2Cpublic_profile&client_id=***. Response for preflight is invalid (redirect)
```
My server is setted like:
```
router.post('/facebook', passport.authenticate('facebook', {
    scope: ['email', 'public_profile']
}));

router.get('/facebook/callback', passport.authenticate('facebook'), (req, res, next) => {
    console.log('hello')
    if (req.user) return res.json(req.user)
});
```
And on the client:
```
export class MyAuthConfig extends CustomConfig{
  defaultHeaders = {'Content-Type': 'application/json'};
  tokenName = 'auth_token';
  authToken = 'JWT';
  providers = {
    facebook: environment.facebook,
    google: environment.google
  };
}
```
On the environment I only have the `clientId` and `redirectUri`
Can't figure out what is the problem.

**Comment by ronzeidman** [comment]
Why is the redirect uri Facebook? It should be your site and should be configured in your Facebook api dashboard

**Comment by mscoobby** [comment]
![Imgur](http://i.imgur.com/F0NwyQx.png)
It is configured to be the localhost.

**Comment by ronzeidman** [comment]
Try setting the redirect URI to the full URI: `http://localhost:9001/auth/facebook/callback` instead of just `http://localhost:9001/`.
Also how do you call the authenticate method? do you subscribe to it?

**Comment by mscoobby** [comment]
I changed the redirect URI still throws the same error. Yes I'm subscribing to the `authenticate` method:
```
  authenticate = (provider) => this.auth.authenticate(provider).subscribe({
    next: (r) => console.log(r),
    error: (err: any) => console.error('Error', err),
    complete: () => this.router.navigateByUrl('/')
  })
```
I guess it's something to do with my server settings but I can't figure out what is wrong.
Facebook is redirecting me to the correct URI in the error the URI is encoded that's why it looks like it's facebook.

**Comment by ronzeidman** [comment]
Look at this fork, Its a bit old but it includes Facebook login, maybe it can help:
https://github.com/MosheBiton/ng2-ui-auth-example

**Comment by mscoobby** [comment]
Can you make an example using PassportJs? I'm trying for days to make this works but I'm receiving the `Response preflight is invalid (redirect)`. I would very appreciate it if you can help me.

**Comment by ronzeidman** [comment]
Since I'm not using PassportJs I can't help you... 
If you've found out what your issue was, please post it so other people will have a solution for this.
I'm closing this issue for now.

**Comment by webdeveloperpr** [comment]
I'm running in to the same issue

**Comment by ClementAntoinette** [comment]
Does somebody find a good issue? I still got this error issue..
