### ISSUE TITLE
Support Request: responseType = 'token'

### ISSUE THREAD

**Issue by AnaRobynn** [ronzeidman/ng2-ui-auth#114]
Hello,

I have the following setup: 
```javascript
import { CustomConfig } from 'ng2-ui-auth';

export const GOOGLE_CLIENT_ID = '442922709156-gk9pnou88asa85rpbm0o3k47pa7gajdd.apps.googleusercontent.com';
export class ExtAuthConfig extends CustomConfig {
	defaultHeaders = { 'Content-Type': 'application/json' };
	providers = { google: { clientId: GOOGLE_CLIENT_ID, responseType: "token" } };
}
```

Calling authService.link('google'), cause the popup to show and a I receive a response, however the token I receive is invalid if I check it a jwt.io?
Is it a problem with my google api setup?
Or with the library?
or with my config of the library?

EDIT: Some further investigation I found out the id_token would be compatible with the JWT, while acces_token is not. How can I ask a id_token from the api's?

Thanks!

**Comment by ronzeidman** [comment]
If you are using response type "token", I do not modify the result received from the authorization server so I can't see where the issue is...

**Comment by ronzeidman** [comment]
closed due to inactivity
