### ISSUE TITLE
Too hard to inherit from JwHttp

### ISSUE THREAD

**Issue by dlnsk** [ronzeidman/ng2-ui-auth#117]
Because you use injection in constructor's parameters it's very difficult to inherit the service.
Here: https://stackoverflow.com/a/39041953 is good explanation how to use Injector in constructor.
You'll get something like this:
```php
import {Injector} from '@angular/core';

@Injectable()
export class JwtHttp {
  private _http: Http;
  private _shared: SharedService;
  private _config: ConfigService;

  constructor(injector: Injector) {
    this._http = injector.get(Http);
    this._shared = injector.get(SharedService);
    this._config = injector.get(ConfigService);
  }
}
```

Also need to export JwtRequestOptionsArgs from module.

**Comment by dlnsk** [comment]
I found solution for my HttpService:
```php
import {Injector} from '@angular/core';

@Injectable()
export class HttpService extends JwtHttp {
  constructor(
    protected injector: Injector
  ) {
    super(injector.get(Http), injector.get(SharedService), injector.get(ConfigService));
  }
}
```
So, breaking changes may will make in major release. But exports JwtRequestOptionsArgs are important now.

**Comment by ronzeidman** [comment]
Thanks, I've been pretty busy the past couple of months so I didn't have time to update this library. I'll do it next week. Probably sooner if you send a PR.

**Comment by ronzeidman** [comment]
I'm working on an angular 5 version of this library, this will remove JwtHttp and will replace it with an interceptor for the HttpClient

**Comment by dlnsk** [comment]
What about export JwtRequestOptionsArgs?

**Comment by ronzeidman** [comment]
It will be removed entirely. the Http service is deprecated in Angular 5+
https://github.com/angular/angular/pull/18906

**Comment by dlnsk** [comment]
Yes, I understude but now in Angular 2 it very necessary. :)

**Comment by ronzeidman** [comment]
Sorry about that...
