### ISSUE TITLE
CSRF cookie?

### ISSUE THREAD

**Issue by epot** [ronzeidman/ng2-ui-auth#118]
Is there a way through configuration to have the POST made by the provider (Google for instance) containing a given cookie? I am trying to write an application doing client-side authentication with this library but it starts failing when I activate CSRF on the server side.

**Comment by epot** [comment]
I am realizing that my description was a bit messed up. Basically, I would like to be able to intercept the calls made by this library to add a cookie in it, but I am not sure how to do that. It was possible with Satellizer as you can see here:
https://github.com/mohiva/play-silhouette-angular-seed/blob/f9bbed9d03ee5da8fafd4a692a67840945d9ac32/ui/app/scripts/app.js

**Comment by epot** [comment]
Basically, I wrote this dirty code to have this working locally, in the class JwtHttp setHeaders method:

        // Add CSRF token for the Play CSRF filter
        const token = this._cookieService.get('PLAY_CSRF_TOKEN');
        if (token) {
            console.log('token ' + token);
            // Play looks for a token with the name Csrf-Token
            // https://www.playframework.com/documentation/2.6.x/ScalaCsrf
            obj.headers.set('Csrf-Token', token);
        }

If this could be configurable, it would be awesome!

**Comment by ronzeidman** [comment]
JwtHttp was deprecated in the latest version. You could probably achieve what you want easily through an interceptor in HttpClient model (new in angular 4.3+) if you want to use it with this library though you will need to upgrade to angular 5 and use the version 8.0.0 (currently on beta) `npm i ng2-ui-auth@8.0.0-beta.2`

I'm closing this for now, tell me if this is still an issue and I'll reopen it.

**Comment by epot** [comment]
Sounds perfect :). Any target date for the release?

**Comment by ronzeidman** [comment]
I'll wait a week. If no critical issues emerge by then I will publish it.

**Comment by epot** [comment]
I am trying to migrate, is there any example up to date with version 8.0.0? I cannot easily migrate with the changelog :(. And any reason it's not officially released?

**Comment by ronzeidman** [comment]
it is officially released. what exactly is the issue? how do you initialize the module?
