### ISSUE TITLE
Angular 5.0.0 upgrade results in \ng2-ui-auth\undefined\ng2-ui-auth.jsError: No module factory available for dependency type: ContextElementDependency

### ISSUE THREAD

**Issue by yoda888** [ronzeidman/ng2-ui-auth#120]
Hi 
Angular 5.0.0 upgraded resulted in compilation fatal error:
\ng2-ui-auth\undefined\ng2-ui-auth.jsError: No module factory available for dependency type: ContextElementDependency

**Comment by ronzeidman** [comment]
I'm working on an angular 5 version, you can look at the beta branch

**Comment by ronzeidman** [comment]
try version 8.0.0-beta.2: `npm i ng2-ui-auth@8.0.0-beta.2` look at the changelog for upgrade details

**Comment by ronzeidman** [comment]
It's the same as before but you don't need to create a class, just an object will work

**Comment by ronzeidman** [comment]
angular 5 is fully supported in version 8.0.0
