### ISSUE TITLE
useClass config removed in 8-beta.2

### ISSUE THREAD

**Issue by timbell** [ronzeidman/ng2-ui-auth#121]
The useClass / CustomConfig support has been removed in beta.2. I was using this to provide the config from a class that injected my own app config service.
 
Would you consider reinstating this functionality?

**Comment by ronzeidman** [comment]
You can use a plain object with the same fields instead of a class now. AOT support is now working in Beta.3

**Comment by timbell** [comment]
My app configuration (including auth) is stored on a server, on a per-app basis. I retrieve this at start-up using a service. I then provide the config to ng2-ui-auth via my service by injecting it into a custom CustomConfig class.

```
@Injectable()
export class AuthConfig extends CustomConfig {
    constructor(private appConfigService: AppConfigService) {
        super();
        this.providers = appConfigService.appConfig.authProviders;
    }
}
...
Ng2UiAuthModule.forRoot(AuthConfig)
```

I don't see how I can achieve the equivalent with the the recent changes.

**Comment by ronzeidman** [comment]
Interesting use case. I'll look into it.

**Comment by ronzeidman** [comment]
try beta 4
provide your own AuthConfig using:
```js
...
{ provide: CONFIG_OPTIONS, useClass: AuthConfig, deps: [AppConfigService] },
Ng2UiAuthModule.forRootWithoutOptions(),
...
```

**Comment by timbell** [comment]
Thanks, yes that works. 
(I had to work around the interceptor injecting my AppConfigService via ConfigService/CONFIG_OPTIONS by forgoing the  use of HttpClient in AppConfigService.)
