### ISSUE TITLE
Decoding french characters from the payload

### ISSUE THREAD

**Issue by gizbo** [ronzeidman/ng2-ui-auth#122]
Hello,
  I just tried the beta 2 branch works great. One minor thing, if any french characters like in french name is encoded in the payload it's not properly decoded. 
For example the name Geneviève come out as GeneviÃ¨ve. 

This seems to cause by :
window.atob(base64) --> shared.service.ts line (74)
 I found this code snippet from stackoverflow that seems to address the issue 
(https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings)
 using the following function does the trick

 function b64DecodeUnicode(str) {
    return decodeURIComponent(Array.prototype.map.call(atob(str), function(c) {
        return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2)
    }).join(''))
}

Thanks,
Yves

**Comment by ronzeidman** [comment]
Thanks, I'll fix it soon

**Comment by ronzeidman** [comment]
try beta 4

**Comment by ronzeidman** [comment]
does it work?

**Comment by gizbo** [comment]
Yep! 
Thanks man,
Yves
