### ISSUE TITLE
pollPopup regression in 8-beta.2?

### ISSUE THREAD

**Issue by timbell** [ronzeidman/ng2-ui-auth#123]
If options.redirectUrl contains a path (eg http://myserver.com/a_path) then this [test](https://github.com/ronzeidman/ng2-ui-auth/blob/7445768db76046a32fede7e5cd9d88b7399fcd5e/src/popup.service.ts#L95) in pollPopup will fail. 

Previously it was testing `popupWindowOrigin === documentOrigin`. I guess an alternative would be to reverse the test: `if (redirectUri.indexOf(popupWindowOrigin) === 0)...` (Probably a good idea to add a '/' to the end of popupWindowOrigin in that case.)

**Comment by ronzeidman** [comment]
try beta.5

**Comment by timbell** [comment]
perfect, thanks!
