### ISSUE TITLE
8-beta.4 fails to load under SystemJS

### ISSUE THREAD

**Issue by timbell** [ronzeidman/ng2-ui-auth#125]
`Error: (SystemJS) XHR error (404 Not Found) loading http://foo.baz.com/appd/app1/node_modules/rxjs/operators.js`

...

`Error loading http://foo.baz.com/appd/app1/node_modules/rxjs/operators.js as "rxjs/operators" from http://foo.baz.com/appd/app1/node_modules/ng2-ui-auth/bundles/ng2-ui-auth.umd.js`

**Comment by ronzeidman** [comment]
Seems you have an older version of rxjs. the beta uses Rxjs 5.5.0+ that have the new "lettable" operators that seems missing from your version

**Comment by timbell** [comment]
No, I'm on 5.5.2. I think it's a SystemJS [thing](https://github.com/ReactiveX/rxjs/issues/2971) (though that's an internal rxjs issue). I added the following to my systemjs.config.js to get around it:

```
map: {
...
  'rxjs/operators': 'node_modules/rxjs/operators/index.js'
}
```

**Comment by ronzeidman** [comment]
I'm guessing it will be common in any library using the new rxjs operators... I'm closing this issue. If you think there is a way I could mediate this in my end feel free to reopen this.
