### ISSUE TITLE
storageType = "none"

### ISSUE THREAD

**Issue by timbell** [ronzeidman/ng2-ui-auth#126]
I set `options.storageType` to `<any>"none"` so that ng2-ui-auth doesn't set any cookies/storage as I handle authorization in my own interceptor. Up to now, this has been ok (apart from the console warning "none is not available") and with 8.0 it still works but both interceptors (mine and ng2-ui-auth's) are setting the authorization header, which isn't great.

Could an official storageType of "none" be added? The handling would be limited to the storage service I think - `get` would always return null/undefined, `set` and `remove` would do nothing. And the interceptor would be deactivated as `shared.isAuthenticated` would be false.

**Comment by ronzeidman** [comment]
Done, try beta 6

**Comment by timbell** [comment]
Really sorry, but I realize now that this won't work. I call `AuthService.getToken` to get the token produced by `AuthService.authenticate`. I was conflating two separate requirements in an effort to simplify things and confused myself in the process! What I'd like is:
- a clean way to tell the `StorageService` to use its internal store rather than storage / cookies
- a way to deactivate the interceptor processing

Can I suggest reverting the current changes and doing the following (I've tested locally this time to be sure that what I'm asking for actually works)

- use internal store
    - add a new storageType `'internal'`
    - at the top of `BrowserStorageService.checkIsStorageAvailable` add:
    ```
    if (options.storageType === 'internal') {
        return false;
    }
    ```
    - in `BrowserStorageService.constructor` change the `if` test for the "storage available" warning:
    ```
    if (!this.isStorageAvailable && config.options.storageType !== 'internal') {
        console.warn(config.options.storageType + ' is not available.');
    }
    ```
- deactivate interceptor
    - add a new config option `deactivateInterception`
    - at the top of `JwtInterceptor.intercept` add:
    ```
    if (this.config.options.deactivateInterception) {
        return next.handle(req);
    }
    ```

**Comment by ronzeidman** [comment]
try beta.7, you can use storageType=MEMMORY and in the forRoot you can choose not to inject the interceptor by setting the second parameter to `false` (`Ng2UiAuthModule.forRoot({... options}, false)`)

**Comment by timbell** [comment]
Thanks, sounds good. MEMMORY should be MEMORY, right?

I've npm updated and the `Ng2UiAuthModule.forRootWithoutOptions` entry point seems to have gone? The sources on github aren't up to date as I write so not sure exactly what's going on there.

**Comment by ronzeidman** [comment]
*thanks... beta.8...

I've removed the `forRootWithoutOptions` just set `undefined` as the first parameter and it should work the same.

**Comment by timbell** [comment]
All working nicely, thank-you very much!
