### ISSUE TITLE
Example for 8.x

### ISSUE THREAD

**Issue by KANekT** [ronzeidman/ng2-ui-auth#128]
> defaultHeaders - No need, you can create your own interceptor.

How ? I need Example :)

**Comment by ronzeidman** [comment]
You can see the guide at Angular's site for using interceptors:
https://angular.io/guide/http#intercepting-all-requests-or-responses

**Comment by ronzeidman** [comment]
updated the example at last:
```
1) git clone https://github.com/ronzeidman/ng2-ui-auth-example.git
2) cd ng2-ui-auth-example
3) npm i
4) replace '<replace me>' tags from /server/src/config.ts and /client/src/config.ts with your google secret and client id 
5) npm start
3) start your browser at localhost:4200
```
