### ISSUE TITLE
Redirect uri not configured

### ISSUE THREAD

**Issue by tomNjerry** [ronzeidman/ng2-ui-auth#130]
When I tried to  implement the satellizer in ionic 3 application it is giving the error of redirect Uri,
since it is ionic framework for mobile  so it is obvious to check for the package name

**Comment by ronzeidman** [comment]
Can you elaborate? where is the check failing? what is the result? what is the suggested behavior?
(I'm not using ionic myself so I rely on community contributions for this support...)

**Comment by fibinger** [comment]
I came across the problem with invalid redirect_uri when using OAuth2. I have a feeling it's the one this topic is about. Facebook rejects connection with following error:

> Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request

When opening OAuth2 popup, the redirect_uri is encoded while it shouldn't be (at least it wasn't in previous versions of this library).
Looks like the function buildQueryString() is much less sophisticated than before, and misses some points.

**Comment by ronzeidman** [comment]
Until now a lot of logic was copy&past from satellizer and it was hard for me to fix issues that people encountered. I've rewritten a lot of parts in version 8 to simplify the logic and make this library more maintainable. So it's reasonable that these kind of issues will happen. What do you expect Facebook should receive as a redirect uri when none is specified? Should it not receive one at all?

**Comment by fibinger** [comment]
I just checked it out. Looks like I was wrong, the problem was not with popup parameter encoding (as a matter of fact it works regardless of encoding).
The thing is that Facebook requires the redirect_uri to have a trailing slashes. For that reason in version 7 of this library it was possible to configure redirection_uri separately per provider:

https://github.com/ronzeidman/ng2-ui-auth/blob/7.0.2/src/config.service.ts#L147

**Comment by ronzeidman** [comment]
You can still configure the redirectUri yourself. as a workaround, you can do so (the default configuration does not include it since it defaults to the origin). I will add this to the defaults in the next version.

**Comment by ronzeidman** [comment]
should be fixed in 8.0.1, please confirm

**Comment by ronzeidman** [comment]
@fibinger can you confirm the fix?

**Comment by fibinger** [comment]
Sorry for a long delay! Tested and all works fine now.
