### ISSUE TITLE
angular 4.4.4 version issue - npm install ng2-ui-auth

### ISSUE THREAD

**Issue by yuvgeek** [ronzeidman/ng2-ui-auth#131]
I use angular 4.4.4 version. Installing npm install ng2-ui-auth requires angular v5, running ng2-ui-auth 7 version requires angular 4.0.0.

What to do?

**Comment by ronzeidman** [comment]
ng2-ui-auth 7 should work with angular 4.4.4 although it won't work with the new HttpClient, only with the original Http. If you want to use the HttpClient you will have to upgrade to 5...
