### ISSUE TITLE
Module is not compiling. Having some build errors

### ISSUE THREAD

**Issue by MalateshPatil** [ronzeidman/ng2-ui-auth#132]
When I am using ng2-ui-auth, I am not able to build it successfully. getting error as shown below. Please help.

![1](https://user-images.githubusercontent.com/18049257/33703482-4dc797ea-db4e-11e7-9f28-fd52e0c125cb.PNG)

**Comment by ronzeidman** [comment]
Seems like you have an old version of typescript. are you using 2.3 or above?

**Comment by MalateshPatil** [comment]
You are correct.
I was having typescript version 2.2. 
Now I have upgraded the typescript version to 2.3.4. Issue resolved. 

Thanks!

**Comment by MalateshPatil** [comment]
Hi Ron Zeidman,

I am using node.js as web service. 
Did this module is only for UI authentication or Shall I use it with passport.js in node.js?

**Comment by ronzeidman** [comment]
You should implement your own server-side endpoints, something similar to https://github.com/sahat/satellizer/blob/master/examples/server/node/server.js
only the parameters the server receives are more organized and look like this:
```
{
    "authorizationData": {
        //the same data sent to the auth endpoint
    },
    "oauthData": {
        //the data received from the oauth endpoint
    },
    "userData": {
        //additional data you've provided
    }
}
```
