### ISSUE TITLE
Support for Universal?

### ISSUE THREAD

**Issue by randomparanoia** [ronzeidman/ng2-ui-auth#135]
Any chance to support angular universal? With last version (8.0.1) compiling start giving issues with window (which is not available on universal). Thanks

**Comment by ronzeidman** [comment]
Can you tell me where exactly? I think I've put all non-universal compatible variables (such as "window") under an `if` condition and it should have been enough, but I guess not.
What's your error?

**Comment by randomparanoia** [comment]
Thanks for your fast response. At moment can't show you, but I believe its the common window not defined. Fast digging in your source code and its related to the next function (utils.ts):

`
export function getWindowOrigin(w = window) {
    try {
        if (!w || !w.location) {
            return null;
        }
        if (!w.location.origin) {
            return `${w.location.protocol}//${w.location.hostname}${w.location.port ? ':' + w.location.port : ''}`;
        }
        return w.location.origin;
    } catch (error) {
        return null;
        // ignore DOMException: Blocked a frame with origin from accessing a cross-origin frame.
        // error instanceof DOMException && error.name === 'SecurityError'
    }
}
`

**Comment by ronzeidman** [comment]
Hmm, can't you put `window` under an "if" statement in Universal? because if it's not defined it should have returned null without an issue (looking at the first condition), I wonder how to fix it then.

**Comment by randomparanoia** [comment]
the actual error:

`
C:\Users\user\Desktop\Dev\Code\app\dist\server.js:216693
    if (w === void 0) { w = window; }
                        ^

ReferenceError: window is not defined
    at getWindowOrigin (C:\Users\user\Desktop\Dev\Code\app\dist\server.js:216693:25)
    at Object.<anonymous> (C:\Users\user\Desktop\Dev\Code\app\dist\server.js:216758:26)
    at __webpack_require__ (C:\Users\user\Desktop\Dev\Code\app\dist\server.js:20:30)
    at Object.JZa/ (C:\Users\user\Desktop\Dev\Code\app\dist\server.js:211073:653794)
    at e (C:\Users\user\Desktop\Dev\Code\app\dist\server.js:211073:158)
    at Object.JwoV (C:\Users\user\Desktop\Dev\Code\app\dist\server.js:211073:662027)
    at e (C:\Users\user\Desktop\Dev\Code\app\dist\server.js:211073:158)
    at Object.Zq8w (C:\Users\user\Desktop\Dev\Code\app\dist\server.js:211073:1056741)
    at e (C:\Users\user\Desktop\Dev\Code\app\dist\server.js:211073:158)
    at Object.0 (C:\Users\user\Desktop\Dev\Code\app\dist\server.js:211073:23068)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@2.10.0 serve:ssr: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@2.10.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-01-16T15_07_36_616Z-debug.log
`

Looking at it, I guess you are right it should have return null, but somehow it bypasses

**Comment by randomparanoia** [comment]
@ronzeidman removing `window` from `export function getWindowOrigin(w = window) {` seems to fix it. But not sure if affects any other logic present in your code.

**Comment by stephengardner** [comment]
@ronzeidman you may want to check `typeof`
`if( typeof window !== 'undefined' ) { ... }`

The error is here:
```
function getWindowOrigin(w) {
    if (w === void 0) { w = window; }
                                  ^
```

**Comment by froodley** [comment]
Any update here?  I am having to fix this with sed during universal compile.

**Comment by froodley** [comment]
There is another line
`popupWindow = window.open(url, windowName, stringifiedOptions);'

Replacing with 
'popupWindow = typeof window !== 'undefined' ? window.open(url, windowName, stringifiedOptions) : null;`

**Comment by ronzeidman** [comment]
I'd appreciate a PR for this since I have been pretty busy in the last couple of months (and still am).

**Comment by ronzeidman** [comment]
try angular6 branch

**Comment by ronzeidman** [comment]
Closed due to inactivity
