### ISSUE TITLE
Error using login with Facebook using an embedded browser.

### ISSUE THREAD

**Issue by jdestradap** [ronzeidman/ng2-ui-auth#139]
Hi guys, 

Just wondering if there is any chance to use your library in order to authenticate with facebook using an embedded browser (facebook app or instagram app). What we think is that when the browser try to open a pop it fails and return the error "Authentication canceled", so is not possible to finished the process. Any advice to resolve this?

Regards,

**Comment by ronzeidman** [comment]
I was experimenting with a different approach using redirects and session storage/cookies and not open a popup at all, but after investigating it, this will require a big rewrite and I'll have to create components, routes and guards in this library for that to work but it will resolve any popup issues. 
What you can do is to implement the redirect approach yourself using this library as a reference for how the OAuth flow works (while you're at it, if you find some part of my code difficult to read you are welcome to ask or add a PR for comments if you've figured it out), and there would be no "popup" issues.
Sorry I couldn't have been more help.

**Comment by timbell** [comment]
Do you see any mileage in (optionally) using an iframe instead of a popup?

**Comment by ronzeidman** [comment]
It's a problem since users would want to see that the URL of the OAuth is the actual SSL "google" or "facebook" url so you won't be giving a different site your actual facebook credentials

**Comment by timbell** [comment]
Right, good point!

**Comment by jdestradap** [comment]
Thanks guys for all your help, I think we will through the first option about implementing based on your library. Cheers!
