### ISSUE TITLE
Twitter redirection not working

### ISSUE THREAD

**Issue by epot** [ronzeidman/ng2-ui-auth#144]
I am trying to use this library with Play! Silhouette on the server side. The issue is that the oauth1 flow is responding a redirect to the ng2-ui-auth library, which is then failing because "No 'Access-Control-Allow-Origin' header is present on the requested resource". I am not sure if the issues lies on the server or client side, but the same server side code is working fine with Satellizer (which apparently is building the Twitter popup url fully on the client side, with no call to the server).
Do you have an idea how I could make this work?

**Comment by epot** [comment]
I can tune the server behavior to send a 200 instead, but I wonder if that is the standard behavior.

**Comment by ronzeidman** [comment]
Seems like a CORS configuration issue. Look here, maybe it can help:
https://www.playframework.com/documentation/2.6.x/CorsFilter

**Comment by ronzeidman** [comment]
Closed due to inactivity
