### ISSUE TITLE
Support for rxjs 6 and angular 6.x

### ISSUE THREAD

**Issue by lafama** [ronzeidman/ng2-ui-auth#145]
Any timelines on when the above will be supported
thank you

**Comment by ronzeidman** [comment]
I'll probably do it when I upgrade my own projects to angular 6 which is when ngrx will release the stable 6 version.

**Comment by ronzeidman** [comment]
try the angular6 branch

**Comment by lafama** [comment]
could we have a beta release for the same?

**Comment by ronzeidman** [comment]
published as `ng2-ui-auth@9.0.0-beta.1`

**Comment by lafama** [comment]
Am getting this on google sigin
``` 
oauthData code is not defined
```
Current response on Google sign in looks as per below
```
{ authorizationData: 
   { response_type: 'code',
     client_id: 'xxxxxxxxxxxx.apps.googleusercontent.com',
     redirect_uri: 'http://xxxxxx:4200',
     scope: 'openid,profile,email' },
  oauthData: 
   { response_type: 'code',
     client_id: 'xxxxxxxxxxxxx.apps.googleusercontent.com',
     redirect_uri: 'http://xxxxxx:4200',
     scope: 'openid,profile,email' },
  userData: {} }
```
What am i missing?

**Comment by lafama** [comment]
Somehow the POST/PATCH url on the my server gets called before the popup has started to authorizes on Google via the popup. I thinks thats why this values are missing

**Comment by ronzeidman** [comment]
probably not, I did an experimental change for help in treeshaking. Instead of:
```
Ng2UiAuthModule.forRoot({providers: {google: { clientId: GOOGLE_CLIENT_ID}}})
```
you should do:
```
Ng2UiAuthModule.forRoot({providers: {google: { ...google, clientId: GOOGLE_CLIENT_ID}}})
```

**Comment by lafama** [comment]
This is what i have. Could i be missing something
```
Ng2UiAuthModule.forRoot({
      tokenPrefix:'xxxxx',
      providers:{
        google:{
            name:'google',
            clientId: 'xxxxxxxx.apps.googleusercontent.com',
            url: '/auth/google',
            method:'PATCH',
            scope:['openid', 'profile', 'email']
          },
        local:{url: '/auth/login',method:'PATCH'}
      }
    })
```

**Comment by lafama** [comment]
This is working now but i think we need to fix this below error
```
ERROR in src/app/app.module.ts(207,29): error TS2345: Argument of type '{ tokenPrefix: string; providers: { google: { clientId: string; url: string; method: string; name...' is not assignable to parameter of type 'IPartialConfigOptions'.
  Types of property 'providers' are incompatible.
    Type '{ google: { clientId: string; url: string; method: string; name: string; authorizationEndpoint: s...' is not assignable to type 'IProviders'.
      Property 'google' is incompatible with index signature.
        Type '{ clientId: string; url: string; method: string; name: string; authorizationEndpoint: string; add...' is not assignable to type 'IOauth1Options | IOauth2Options'.
          Type '{ clientId: string; url: string; method: string; name: string; authorizationEndpoint: string; add...' is not assignable to type 'IOauth2Options'.
            Types of property 'oauthType' are incompatible.
              Type 'string' is not assignable to type '"2.0"'.
``

**Comment by ronzeidman** [comment]
yea... I'll take care of it.

**Comment by lafama** [comment]
If i may ask, why did you decide to add ```...google,``` and going forward when do you plan to have  it fixed?

**Comment by ronzeidman** [comment]
Removed it, the thing is that when you import the library you have to import all the providers as well. this way the unnecessary providers can be tree shaked away. 
This is confusing and will probably cause frustrations in other people adopting the library so I've removed it, now it shouldn't be necessary. try beta.2...

**Comment by lafama** [comment]
Beta 2 works well. I think the idea to import only the needed providers is noble but the documentation would have to be updated to reflect this. I can try help out on that or any other bit. Do let me know
Thank you

**Comment by timbell** [comment]
Beta 2 appears to be missing the export of `IPartialConfigOptions`

**Comment by lafama** [comment]
Hi Timbell,
Kindly check the code i believe you don't need the IPartialConfigOptions interface anymore, use the code as per below
```
import { Ng2UiAuthModule, google } from 'ng2-ui-auth';

Ng2UiAuthModule.forRoot({
      tokenPrefix:'xxxxx',
      providers:{
        google:{
            ...google,
            name:'google',
            clientId: 'xxxxxxxx.apps.googleusercontent.com',
            url: '/auth/google',
            method:'PATCH',
            scope:['openid', 'profile', 'email']
          },
        local:{url: '/auth/login',method:'PATCH'}
      }
    })
```

**Comment by ronzeidman** [comment]
It's still using it internally, I can expose it.
I'm finishing the upgrade to angular 6 of my own projects next week, I'll publish the release version then and will expose IPartialConfigOptions if you need it.

**Comment by surfdew** [comment]
Any update on the official 9.0 release?

**Comment by ronzeidman** [comment]
Published, check if everything is working correctly and I'll close this issue.

**Comment by ronzeidman** [comment]
This file is generated by the cli...
