### ISSUE TITLE
 backend.createConnection is not a function

### ISSUE THREAD

**Issue by royipressburger** [ronzeidman/ng2-ui-auth#15]
Hi again :)

I am trying to extend the `JwtHttp` class becuase I want to able to add some headers to all my requests + doSomething if any request fails. aswell I have added an overload to get and post methods that allow object as body and parameters instade of string

```js
export class MyJwtHttp extends JwtHttp {
  constructor(private backend: ConnectionBackend, defaultOptions: RequestOptions, shared: Shared, config: Config) {
    super(backend, defaultOptions, shared, config);
  }

  request(url: string | Request, options?: RequestOptionsArgs): Observable<Response> {
    options = options || {};
    if (!options.headers) {
      options.headers = new Headers();
    }

    // TODO: expected error for
    options.headers.set('Content-Type', 'application/json;charset=UTF-8');
    return super.request(url, options)
    .catch((err, source, caught) => {
      return Observable.empty();
    })
  }

  post(url: string, data, options?: RequestOptionsArgs):Observable<Response>  {
    return super.post(url, (typeof(data) === 'string' ? data : JSON.stringify(data)), options);
  }

  get(url: string, params?: Object) : Observable<Response> {
    var args: URLSearchParams;
    if (params) {
      args = new URLSearchParams();
      for (let key in params) {
        args.set(key, params[key]);
      }
    }

    return super.get(url, args);
  }
}
```

Im my bootstrap: 

```js
export const MY_HTTP_PROVIDER = [
  ConnectionBackend,
  MyJwtHttp,
  provide(JwtHttp,{
      useFactory:
      (xhrBackend, requestOptions, shared, config, router) =>
      new MyJwtHttp(xhrBackend, requestOptions, shared, config),
      deps: [XHRBackend, RequestOptions, Shared, Config],
    }),
  BrowserXhr,
  provide(RequestOptions, {useClass: BaseRequestOptions}),
  provide(ResponseOptions, {useClass: BaseResponseOptions}),
  XHRBackend
];
```

Now when im doing some random request to my server I get 
`browser_adapter.js:76 ORIGINAL EXCEPTION: TypeError: backend.createConnection is not a function`

any idea? 

Thanks ahead!

**Comment by ronzeidman** [comment]
To add a default header I've provided a configuration:

`NG2_UI_AUTH_PROVIDERS({ defaultHeaders: {'Content-Type': 'application/json'}, providers: {google: {clientId: GOOGLE_CLIENT_ID}}})`

**Comment by ronzeidman** [comment]
You are not using the "backend" variable, try not prefixing it with "private" in the constructor it may be colliding with the definition on the parent Http.

**Comment by royipressburger** [comment]
Regarding the headers its working but one question, If i want a request without the defualt value is that possiable?

And is till get the same error regarding the `backend`, 
For some reason when debugging its looks like the `backend` is an empty `ConnectionBackend` object, but its not like that in `MyJwtHttp` constructor, On init its looks ok. but when dispacing a request... :-1:

**Comment by ronzeidman** [comment]
To not use the default you just have to pass the headers through the options.
I havent read everythin in full because I'm on my phone but the issue is probably some conflict in variables in the "inheritance" mechanism (the prototypical inheritance is a bit tricky in es6/typescript). If you'll look on the transpiled JavaScript you might get a better clue.
I won't be working through this weekend so I'll only be able to help you further afterwards.

**Comment by ronzeidman** [comment]
The internal mechanism of ng2-ui-auth must work with plain JwtHttp (or something "compliant") so if you want to override the default behavior of JwtHttp you can provide MyJwtHttp instead. notice that JwtHttp is provided now with all other NG2_UI_AUTH_PROVIDERS so you don't need to provide it yourself but in order for it to work properly the XHRBackend and RequestOptions must be provided beforehand, meaning you should also provide HTTP_PROVIDERS:
```ts
bootstrap(app, [HTTP_PROVIDERS, NG2_UI_AUTH_PROVIDERS(...), MyJwtHttp])
```
that way in the internal ng2-ui-auth mechanism the JwtHttp is used and you can use your MyJwtHttp wherever you'd like. 

To replace the JwtHttp in the internal ng2-ui-auth mechanism you should make your own "HTTP_PROVIDERS" and "NG2_UI_UATH_PROVIDERS" and provide all the classes the way you'd like.

That's if I understand the issue, if not please clarify what you want to achieve.

**Comment by royipressburger** [comment]
Well I dont really know what is the excect problem, but I solved with by wrapping the JwtHttp instead of inherit from it
