### ISSUE TITLE
deploying ng2-ui-auth-example to a public domain

### ISSUE THREAD

**Issue by tuhin24** [ronzeidman/ng2-ui-auth#151]
Hello Ron,

I am trying to deploy my app to my domain and having some difficulties. It works fine using localhost.

I put my node server on an azure domain which is running on port 3000. I can access it from outside.

I built the client using ng build --prod  and copied everything from dist folder to my domain at hostgator.com . Now I can access my domain directly without any port. When I click on login to facebook, I get facebook's login dialog. Once I put my credentials. I get the following error:
"Http failure response for http://www.mydomain.com/auth/facebook: 404 Not Found"

Any tip on how to fix this?

Regards,

**Comment by ronzeidman** [comment]
Sorry I wasn't available in the past few months, anyway I'm guessing the question is no longer relevant but just for reference, if your server returns 404 try to test it using postman.

**Comment by tuhin24** [comment]
Hello Ron,
I may have found the problem I am facing in my production environment. In my example, I have a proxy.conf.json file that has. 

{
  "/auth": {
    "target": "http://localhost:3000"
  }
}
In my dev env I run it using:
ng serve --proxy-config proxy.conf.json --aot and it works fine.

For production environment, I build it using
ng build --prod

I copy the file from dist folder to my Apache server. Unfortunately, in production proxy.conf.json  not used. so any call to  http://www.mydomain.com/auth/facebook fails. I am stuck here for a week. Any help is highly appreciated. Thanks

**Comment by ronzeidman** [comment]
Read here: https://angular.io/guide/deployment#server-configuration

There is a specific section there about Apache configuration. Read it
carefully since you'll need to understand why and how the configuration
works.
