### ISSUE TITLE
Twitter login is getting blocked by the popup blocker in chrom

### ISSUE THREAD

**Issue by tuhin24** [ronzeidman/ng2-ui-auth#153]
Hi Ron,

I appreciate all your support. Now that I deployed my app I have one problem I would like to resolve. 
My FB/Linkedin/ login works fine but logging with twitter gets blocked by the pop-up blocker. If I enabled the URL then twitter login works. Is there anything I can do to avoid getting the twitter login blocked?

Thanks in advance for your response.

**Comment by ronzeidman** [comment]
Hi,
In oauth1 there is an initial step (server call) that's need to be done before opening the popup, that step may be the culprit of this issue, I'll try to fix it - open the popup with about:blank before getting the authorization data and then navigate the popup to the right url but that may take time, if you'd like to contribute you are more than welcome (https://github.com/ronzeidman/ng2-ui-auth/blob/master/projects/ng2-ui-auth/src/lib/oauth1.service.ts) the popup needs to be opened before the  `http.post` call and then redirected to the url with the authorization data. (the popup service will need to change a bit to support that).

**Comment by tuhin24** [comment]
Ron, I could not fix it. I will wait till get some time to fix it. Thanks again for your help.

**Comment by tuhin24** [comment]
Hello Ron,

I am checking to see if you would be able to get some time to fix twitter popup blocker issue. Looking forward to a fix for this..

Regards,
Tuhin
________________________________

**Comment by tuhin24** [comment]
Thanks Ron! I tried to get the branch using

npm install --save ronzeidman<https://github.com/ronzeidman>/ng2-ui-auth<https://github.com/ronzeidman/ng2-ui-auth>#twitter_popup<https://github.com/ronzeidman/ng2-ui-auth/tree/twitter_popup>

but it is creating ng2-ui-auth-project  in package.json. Maybe I am doing something wrong.   Any tip on how to install this branch?

Thanks
________________________________

**Comment by ronzeidman** [comment]
No, you're doing nothing wrong, but the GitHub version doesn't contain the compiled just, you'll habe to clone it, compile it using `npm run build` and then npm install from local disk path `<cloned repo>/dist/ng2-ui-auth`

**Comment by ronzeidman** [comment]
After npm install

**Comment by tuhin24** [comment]
Thanks, Ron! I ran npm install then npm run build. Fixed a few issues along the way but now I am getting:

Could not find module "@angular-devkit/build-ng-packagr"

Googling did not help much.

This may not be the last issue before I am able to compile it. I am wondering if it would be possible for you to upload the compiled version for me to test?

Thanks,


________________________________

**Comment by ronzeidman** [comment]
I've committed the compiled targets, you should be able to install it by `npm i ronzeidman/ng2-ui-auth#twitter_popup`

**Comment by tuhin24** [comment]
Hello Ron,

Thanks for your help. I have tested this and it looks great. I am not getting popup blocker blocking twitter login dialog anymore.
I tested only with Chrome and my test was limited to this specific feature. I did not test for any regression.

I will do some more tests tonight. Thanks again for your help. I truly appreciate it!

Regards,
Tuhin

________________________________

**Comment by tuhin24** [comment]
Hello Ron,

I did further testings with other browsers and it looked great.

Thanks,
Tuhin
________________________________

**Comment by ronzeidman** [comment]
Great, I'll merge and publish the new version

**Comment by ronzeidman** [comment]
included in v9.2.1
