### ISSUE TITLE
TypeError: Object(...) is not a function on Popup service And popup is also not closing once logged in

### ISSUE THREAD

**Issue by RanjeetAvghad** [ronzeidman/ng2-ui-auth#154]
Hi and Thanks for great work.

I have following configuration.
`outlook: {
                    clientId: environment.outlook.appID,
                    authorizationEndpoint: environment.outlook.authEndpoint,
                    responseType: "id_token token",
                    scope: environment.outlook.scope,
                    redirectUri:"http://localhost:4200",
                    scopeDelimiter: " ",
                    state: guid(),
                    additionalUrlParams:{
                        nonce:guid()
                    }
                },`
i am able to login but its not closing popup also while opening popup i can see following error in 
console

 TypeError: Object(...) is not a function
    at PopupService.open (ng2-ui-auth.js:841)
    at Oauth2Service.open (ng2-ui-auth.js:1142)
    at OauthService.authenticate (ng2-ui-auth.js:1271)
    at AuthService.authenticate (ng2-ui-auth.js:1429)
    at LoginComponent.signInWithOutlook (login.component.ts:93)

Help me.

Attaching the screenshot of debugger it seems operator **of** is not defined.
![image](https://user-images.githubusercontent.com/20903058/51591186-51936f80-1f12-11e9-9429-fd1c72f83cbf.png)

**Comment by ronzeidman** [comment]
It seems you have something wrong with your rxjs version reference. what version are you using?
