### ISSUE TITLE
skipAuthentication: true?

### ISSUE THREAD

**Issue by royipressburger** [ronzeidman/ng2-ui-auth#17]
Is there a way right now to skip the attachment of the authentication header?

**Comment by ronzeidman** [comment]
Use the basic HTTP service instead of the JwtHttp?

**Comment by royipressburger** [comment]
Doesn't work.. It seems like the `JwtHttp` is being use even if I use the basic `Http` service.

**Comment by ronzeidman** [comment]
Can you show me how you bootstrap the HTTP providers?

**Comment by royipressburger** [comment]
Im sorry I did injected JwtHttp
