### ISSUE TITLE
Set `authenticate` post headers to use 'application/json'

### ISSUE THREAD

**Issue by seansean11** [ronzeidman/ng2-ui-auth#18]
I've added support to my API for plain/text in order to handle requests from the oAuth2 class in the library.  I'd like to send my requests as 'application/json'. With the login and signup methods, I'm able to pass headers into the options parameter, which is how I was working with those methods.  I looked through the code, but it didn't look like this is possible with the `authenticate` method.  Is there a way to set the post headers to 'application/json', or is it currently not possible?

**Comment by royipressburger** [comment]
Why not set default headers as json?

```js
 NG2_UI_AUTH_PROVIDERS({ defaultHeaders: {'Content-Type': 'application/json'},
     providers: {
        google: {clientId: '***'}
        facebook: {clientId: '***'}
      }
    }),
```

This will make every request send with `JwtHttp` to attach `application/json` header.
and if you want different header to some requests you can just pass in the paramters different headers and will override the default.

**Comment by seansean11** [comment]
Wow, I can't believe I missed that.  Thanks for the swift response @royipressburger.
