### ISSUE TITLE
Getting ng2-ui-auth works with passport.js

### ISSUE THREAD

**Issue by lygstate** [ronzeidman/ng2-ui-auth#24]

**Comment by ronzeidman** [comment]
You could use this library with passport js by changing the redirectUri of the providers to your passport js endpoint:
```ts
bootstrap(Main, [
    HTTP_PROVIDERS,
    NG2_UI_AUTH_PROVIDERS({
        defaultHeaders: DEFAULT_POST_HEADER, 
        providers: {
            google: {
                clientId: GOOGLE_CLIENT_ID,
                redirectUri: '/auth/google/callback',
            }
        }
    }),
]);
```
server-side
```ts
app.get('/auth/:provider/callback', passportAuthenticate, function(req, res) {
  res.redirect(req.session.returnTo || '/');
});
function passportAuthenticate(req, res, next) {
      passport.authenticate(req.params.provider)(req, res, next);
}
```
I think (didn't test it), If you are able to make it work please add a comment describing the steps or telling if it works.

more about this issue:
https://github.com/sahat/satellizer/issues/560

**Comment by ronzeidman** [comment]
I'm closing this issue for now, if someone can give a tested example of passportjs working with this library he is welcome to publish here + add a pull request for ng2-ui-auth-example.
