### ISSUE TITLE
line 35 in local.ts prevent sending request with the user data in the body should be updated like line 21

### ISSUE THREAD

**Issue by yahyaKacem** [ronzeidman/ng2-ui-auth#25]
Hi, thanks for the fix in #19, I think the register also should be fixed the same as #19 in the line [35](https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/local.ts#L35) of local.ts.
I'll make a pull request for it.

**Comment by ronzeidman** [comment]
included in version 3.0.4
