### ISSUE TITLE
property missing in ICustomConfig?

### ISSUE THREAD

**Issue by dmeatte** [ronzeidman/ng2-ui-auth#27]
Should ICustomConfig in ng2-ui-auth/declerations/config.d.ts define authHeader? It's implemeted in Config and the code uses it, but it's not in the interface and is causing errors for me. Thanks.

**Comment by ronzeidman** [comment]
You're right, it's just the interface that was missing. try version 3.1.1

**Comment by dmeatte** [comment]
Thanks. That worked.
