### ISSUE TITLE
Facebook clientId is not returned to local server

### ISSUE THREAD

**Issue by sunild** [ronzeidman/ng2-ui-auth#31]
Doing Oauth2 with Facebook. I've verified through the debugger that the Oauth2 class is starting the exchange w/Facebook correctly and passing my clientId to them.

However, when the popup window receives the Facebook response and sends it to my server, the clientId is not sent to my server, so it fails to get a token.

The server is working w/Satellizer and our existing Angluar 1 app. Having a hard time debugging the code that is running inside the pop up window, so this is as far as I got.

Sorry I can't be much more help, but am happy to help out in any way I can ... I think I might need some direction w/this one.

**Comment by martinop** [comment]
I have a problem, im working with satellizer in a existing Angular 1 App, Now i need to use this ng2-ui-auth buth what is the url that i need to put in redirectUri? If i put the same of the Angular 1 App the popup render the Angular 1 App, and if i dont put the redirecturi of angular 1 app get the "Redirect Uri not match, i need to create other instagram app?

**Comment by ronzeidman** [comment]
@martinop I think you can configure Instagram to not enforce redirect uri, or at least be able to add a few redirect Uris (I know that in a google app you can add a few acceptable redirect uris) look into Instagram app configuration.

**Comment by ronzeidman** [comment]
@sunild I know, there is an issue debugging the closed window, you can disable the "window close" and then debug.
I'll try and create a facebook & twitter app for testing and get back at you with results

**Comment by sunild** [comment]
Thanks for the debugging tip! I'll remember that for next time.

This one turned out to be an error on my part, the clientId was being sent properly ... Introduced a new version of our API which was causing the problem. Sorry for the false alarm!
