### ISSUE TITLE
OAuth 1.0a help

### ISSUE THREAD

**Issue by larssn** [ronzeidman/ng2-ui-auth#32]
Hi, thanks for the effort.

I've been trying to get a simple 3-legged OAuth 1.0a example up and running, and been kinda lost.

3-legged OAuth 1 requires 3 steps, first sending your oauth_consumer_key and oauth_signature to a "request" url, to get the oauth_token and oauth_token_secret back. I cant, however, figure out where to enter these parameters in the config.

I humbly ask for a simple OAuth 1 example. Maybe against twitter.

Ps. This is in the context of an Ionic 2 setup btw.

**Comment by ronzeidman** [comment]
I actually started working on creating a Twitter example but I have some urgent issues in my actual work so it might take until the weekend to create. Stay tuned :)

**Comment by larssn** [comment]
Thank you! 👍 

Is there a lot of coding involved getting it to work? Compared to the existing Ionic 2 example, that is.

**Comment by sunild** [comment]
@larssn  I just got Twitter authentication working and can at least confirm you don't need to do anything special for the configuration of this library. Most of the work is on the server side ... to implement that I recommend digging around on the Satellizer site's examples directory and the section on "login flows". 

Your backend will get two requests during authorization. On the first one, the query parameters will not include the `oauth_token` and `oauth_verifier` parameters. If these params are missing from the request, you server should start the process of getting a request token from twitter.

On the second request, those two query parameters will be part of the request, and you can use them to get the access token from Twitter.

The implementation of the above depends on your server...

**Comment by sunild** [comment]
@larssn Sorry, I may have jumped the gun... I thought I was also doing the 3 legged Oauth, but am not. For 3 legged Oauth, you need to change the `authorizationEndpoint` as specified [here](https://dev.twitter.com/oauth/3-legged).

So your config might look like this:

```
import { Config } from 'ng2-ui-auth';

export let authConfig = new Config(
  {
    defaultHeaders: DEFAULT_HEADERS,
    providers: {
      twitter: {
        authorizationEndpoint: 'https://api.twitter.com/oauth/authorize'
      }
    }
  }
);
```

**Comment by larssn** [comment]
@sunild Thanks for taking the time to try this out!

I've been trying to do this with a custom 3-legged OAuth 1.0a endpoint (against wordpress), and I don't understand where to input the request and access endpoints.

To clarify:
I need to specify:
localhost/oauth1/request
localhost/oauth1/authorize (this I know how to set: authorizationEndpoint)
localhost/oauth1/access

Not sure how to define the first and the last endpoint.

**Comment by sunild** [comment]
@larssn Not sure I can help much further, I think this is very specific to Wordpress... The steps to get the request and access token would be performed by Wordpress (or a plugin, etc.), as such  there should be no need to configure those endpoints in ng2-ui-auth.

**Comment by larssn** [comment]
Don't worry about it :)

But I don't think it's specific for Wordpress, I've been reading up on 3-legged OAuth 1.0a (http://oauthbible.com/#oauth-10a-three-legged) and unless I'm completely misunderstanding it, the app and the service needs to communicate 3 times (the RFC also mentions this: https://tools.ietf.org/html/rfc5849#section-1.2); and my confusion comes from the fact that I can only enter a single endpoint. Maybe some OAuth 1.0a implementations use the same endpoint? - I don't know, I'm still learning.

Anyway, decided to write my own tiny wordpress client library, as I been looking far and wide, and haven't been able to find a library that supports 3 distinct endpoints.

But thanks again for trying to help, appreciate it! :)

**Comment by ronzeidman** [comment]
@larssn Done, it works.
I've updated the example to show how to do a 3 legged authentication. (the server contacts twitter twice and the client once)
It seems to work fine without special configuration (please use version 3.2.2 of ng2-ui-auth)

**Comment by larssn** [comment]
Thanks, helpful!
