### ISSUE TITLE
Catch popup close event

### ISSUE THREAD

**Issue by benjaminb-** [ronzeidman/ng2-ui-auth#33]
Hi,

It's possible to catch the popup close event ?

Thanks !

**Comment by ronzeidman** [comment]
What do you when to do when it happens?
You can add a hook to the Popup class somewhere before this line: https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/popup.ts#L72
If you make something generic you can create a pull request, if not you can replace the popup class by inheriting from it and providing it to the bootstrap
