### ISSUE TITLE
ng2-ui-auth cant be found

### ISSUE THREAD

**Issue by nigel-dewar** [ronzeidman/ng2-ui-auth#35]
Hi Rod, 

I went through the process of doing a 'clean as possible' install of ng2-ui-auth but browser console complains that ng2-ui-auth cannot be found.

Here is what I did. I cloned a fresh copy of the angular starter from Angular.io which includes all the up to date goodies.

I installed, and run, worked great.

I did an npm install ng2-ui-auth --save, all looks well, package came down sweet. 

In my main.ts I setup like so

import { bootstrap }    from '@angular/platform-browser-dynamic';
import {provide} from '@angular/core';
import {HTTP_PROVIDERS} from '@angular/http';
import {NG2_UI_AUTH_PROVIDERS, JwtHttp} from 'ng2-ui-auth';
import { AppComponent } from './app.component';

const DEFAULT_POST_HEADER: {[name: string]: string} = {
  'Content-Type': 'application/json'
};
const GOOGLE_CLIENT_ID = '******************************.apps.googleusercontent.com';

bootstrap(AppComponent, [
    HTTP_PROVIDERS,
    NG2_UI_AUTH_PROVIDERS({defaultHeaders: DEFAULT_POST_HEADER, providers: {google: {clientId: GOOGLE_CLIENT_ID}}}),
]);

tried to run and bang this is where I hit trouble, 

Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3000/ng2-ui-auth

Any ideas?

Cheers

**Comment by nigel-dewar** [comment]
Hi Rod, in the end I had to do this to get it working... not sure if this is the best way moving forwards though.

 import {NG2_UI_AUTH_PROVIDERS} from '../node_modules/ng2-ui-auth/dist/ng2-ui-auth'; 

What do you think? Is there something wrong with the npm package or my project and how it interprets NPM packages. Its like it cant find the dist folder and go to the right place, ng2-ui-auth.js...

Any light on this would really help. 

Cheers

Nigel

**Comment by ronzeidman** [comment]
Are you using webpack out system js? Seems like you haven't configured it

**Comment by ronzeidman** [comment]
Resolving packages in the browser the way node resolves files is expensive over the web, it first reads the individual package.json file for the main file and only then the actual file. when you require in node a file it first attempts to get a file with that name, then checks if it's actually a folder and then takes the index.js file in that folder. the browser cannot afford all these round-trips so all configuration should be in one files and all files should be explicitly imported. What you need to do is to add my package to the package configuration file:
https://github.com/angular/quickstart/blob/master/systemjs.config.js
you need to add to the "map" section the ng2-ui-auth folder: `'ng2-ui-auth': 'node_modules/ng2-ui-auth'`
also you'll need to add the main file and default extension to the packages:
`'ng2-ui-auth': { main: 'dist/ng2-ui-auth.js', defaultExtension: 'js' }`
I think that should cover it.

**Comment by nigel-dewar** [comment]
Hi Rod, yes sorry I did manage to figure this out, and I didnt see your response till now as github mail was going into my damn junk box.

I ended up doing this and got it all working in my systemjs.config.js

  var map = {
    'app':                        'app', // 'dist',

    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs',
    // 'zone.js':                    'node_modules/zone.js/dist/zone.js',
    'ng2-ui-auth':                'node_modules/ng2-ui-auth/dist/ng2-ui-auth.js'
  };

  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    // 'zone.js':                       { defaultExtension: 'js' },
    'ng2-ui-auth':                { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
  };

So just so I understand, is it the case that JSPM is the preferred way?, 
I mean, is there a significant advantage to using JSPM as apposed to traditional method? Is this what you are saying? 

I think ng2-ui-auth is brilliant by the way, Ive spent the last couple of weeks going through it, seeing how you put it together and getting an understanding about how angular2 fits together and uses rxjs.

Cheers for your work, and apologies for bothering you with noob stuff like this.

Nige.

**Comment by ronzeidman** [comment]
That works too,.
Thanks, I prefer using JSPM since it manages my external modules automatically, but it's not without its downsides/overheads mostly because editors don't recognize the JSPM path mappings automatically so you either need to smartly configure the editor (if you can) or install dependencies in both JSPM and npm. So if you don't have many dependencies or your dependencies are not complex you should probably stick to manual configuration.

Thanks for the compliments :) I'm glad my code is able to teach people. We are all noobs in angular2 since its a new and always changing framework so we all have a lot to learn.

Cheers,
Ron

**Comment by nigel-dewar** [comment]
Thanks very much Ron,

If you ever need anyone to do any tutorials, or expanded doco for ng2-ui-auth, hit me up.

Actually I was thinking about doing a youtube video showing how to use ng2-ui-auth. Would you be ok with that? Full credit to yourself and your library of course.

Nige.

**Comment by ronzeidman** [comment]
:+1: I'd be honored.
Also you should probably give credit to @sahat https://github.com/sahat/satellizer he was the one that built the original angular1 library, I just needed one for angular2 so I converted it.

**Comment by nigel-dewar** [comment]
Absolutely. Credits to sahat and yourself.

Alot of folks will benefit from your hard work.

Cheers Ron.


Sent from Samsung Mobile


-------- Original message --------
From: Ron Zeidman
Date:25/07/2016 14:57 (GMT+10:00)
To: ronzeidman/ng2-ui-auth
Cc: nigel-dewar , State change
Subject: Re: [ronzeidman/ng2-ui-auth] ng2-ui-auth cant be found (#35)


👍 I'd be honored.
Also you should probably give credit to @sahat<https://github.com/sahat> https://github.com/sahat/satellizer he was the one that built the original angular1 library, I just needed one for angular2 so I converted it.
