### ISSUE TITLE
authorization for custom authentication provider

### ISSUE THREAD

**Issue by manura** [ronzeidman/ng2-ui-auth#36]
hi ronzeidman,

Thanks for your effort first. I'm trying to use your library for a project. I'm trying to use it with a custom jwt authentication provider .previously I have used the custom jwt authentication provider with satellizer successfully. 

Here is how I used it with satellizer.

$authProvider.oauth2({
      name: 'customauthprovider',
      url: '/auth/custom',
      clientId: 'abc',
      redirectUri: window.location.origin,
      authorizationEndpoint: CONFIGS.imsmartBaseUrl + 'oauth/authorize'
    });

jwt authentication is developed with asp.net mvc and oauth2.

My feeling is ng2-ui-auth should support with custom authentication providers as well. But when  I try it use it I face some issues.

import {NG2_UI_AUTH_PROVIDERS} from 'ng2-ui-auth';

bootstrap(AppComponent, [
    HTTP_PROVIDERS,
    appRouterProviders,
    NG2_UI_AUTH_PROVIDERS({
        providers: {
            oauth2: {
                 name: 'customauthprovider',
                 url: '/auth/custom',
                 clientId: 'abc',
                  redirectUri: window.location.origin,
                  authorizationEndpoint: CONFIGS.imsmartBaseUrl + 'oauth/authorize'
            }
        }
    }),
]);

and my login component is 

import {Component, OnInit, AfterContentInit, ElementRef, Renderer} from '@angular/core';
import {Auth} from 'ng2-ui-auth';
import {ROUTER_DIRECTIVES, Router} from '@angular/router';

@Component({
    selector: 'login-view',
    templateUrl: 'app/login/login.component.html',
    styleUrls: ['app/login/login.component.css']
})
export class LoginComponent implements OnInit, AfterContentInit {

    constructor(
        private router: Router,
        private auth: Auth,
        private element: ElementRef,
        private renderer: Renderer ) {}

    ngOnInit(){

    }

    ngAfterContentInit(){
        this.renderer.setElementClass(this.element.nativeElement, 'app', true);
        if (this.auth.isAuthenticated()) {
            this.navigateToSegments();
        }
    }

    authenticate(provider: string) {
      alert(provider);
        this.auth.authenticate(provider)
            .subscribe(() => this.navigateToSegments());
    }

    navigateToSegments() {
        let link = ['/segment'];
        this.router.navigate(link);
    }
}

When I try it I got the following error
![ng2-ui](https://cloud.githubusercontent.com/assets/6085777/17106095/a048bf84-52a7-11e6-819e-1cf8aed3795a.png)

And then I have tried to import the  import {Oauth} from 'ng2-ui-auth';
but it give the following error on compile. 

#node_modules/ng2-ui-auth/dist/ng2-ui-auth"' has no exported member 'Oauth'.#

I also try to change the ng2-ui-auth.d.ts file as well . but couldn't make it. 

Can you help me to use it or customize it for a custom authentication provider. Thanks in advanced.

**Comment by ronzeidman** [comment]
I didn't export the oauth class from the main file, you can import it from the source although I don't think you'll need it. The error seems to tell that there is no such provider, since you didn't show the html I don't know what value your "provider" variable has, but it should be "oauth2" since that's the new provider you've provided.
You should be able to debug the oauth.ts (https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/oauth.ts#L23) to see if your provider exists and the config.ts (https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/config.ts#L80) to see if the bootstrapping added the configuration (you should be able to debug them directly since the source mapping is included, just add a breakpoint in chrome it will catch the error).
Update me with the results.
Thanks!

**Comment by manura** [comment]
Thanks ronze,
 I have managed to make the authentication done. It was wrong name I have called from the html. Now it get authenticated and gets the token from the server.

But how do you set the ng2-ui-auth_token in the example app. I see 

  getToken(): string {
        return this.shared.getToken();
    }
    setToken(token: string): void {
        this.shared.setToken(token);
    }
methods in the auth.ts. but where you call them in the example and set the token

**Comment by ronzeidman** [comment]
Great, as you can see here https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/oauth.ts#L30 and here https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/local.ts#L33 I automatically set the authentication token after "authentication" and "login" method automatically. You can set the token manually if you get it by other means but it's not necessary.
