### ISSUE TITLE
config for API running on different url or port

### ISSUE THREAD

**Issue by nigel-dewar** [ronzeidman/ng2-ui-auth#37]
Hi Ronz, 

I was in process of doing more experimentation, and can't find any place where there is a central constant for a different backend api url or port.

Is there one? And Im just missing it. It looks to me like the library will send back to same url and port all the time 'localhost:3000'

But what if a person is using http://localhost:5000 for instance for a backend api. Is there one place I can enter this constant and API calls will go to this url?

Cheers

**Comment by ronzeidman** [comment]
Hi, You can! just add baseUrl to the config: `NG2_UI_AUTH_PROVIDERS({ baseUrl: 'localhost:5000' ....})` and it should work (by default the baseUrl is '/' so it's the same as the site's Url)

**Comment by nigel-dewar** [comment]
Oh Sweet! thanks Ron , I should have seen that.

Thank you

**Comment by sylc** [comment]
For info: 
baseUrl: 'localhost:5000' is not working for me. 
But baseUrl: 'http://localhost:5000/' is working.
