### ISSUE TITLE
Error - No provider for Auth !

### ISSUE THREAD

**Issue by BansheeHood** [ronzeidman/ng2-ui-auth#42]
Hi,

An error occurred while authenticating and I have no idea why... It is the same code as you use on your ng2-ui-auth-example : 

![sans titre](https://cloud.githubusercontent.com/assets/21682157/18312750/7f380012-750b-11e6-9233-37e87c5b6b29.png)

Here is my DashboardComponent : 

`import { Auth, JwtHttp } from 'ng2-ui-auth';
import { ROUTER_DIRECTIVES, Router } from '@angular/router';
import { Component } from '@angular/core';
import { Observable } from 'rxjs/Rx';
import { TranslatePipe } from 'ng2-translate';

@Component({
    selector: 'app-overview',
    templateUrl: '../views/dashboard.html',
    directives: [ROUTER_DIRECTIVES],
    pipes: [TranslatePipe]
})

export class DashboardComponent {
    userName: Observable<string>;

    constructor(private _auth: Auth,
        private _router: Router,
        private _jwtHttp: JwtHttp) {
        this.userName = _jwtHttp.get('/api/userName').map((response) => response.text());
    }

    goToLogin() {
        this._router.navigate(['/login']);
    }

    logout() {
        this._auth.logout().subscribe(() => {
            this.goToLogin();
        })
    }
}`

**Comment by ronzeidman** [comment]
What's the code in your `NgModule` class?

**Comment by BansheeHood** [comment]
Here it is (RC.4 - Bootstrap.ts) : 

`import 'zone.js/dist/zone.js';
import 'reflect-metadata';

import { bootstrap } from '@angular/platform-browser-dynamic';
import { provide } from '@angular/core';
import { HTTP_PROVIDERS, Http } from '@angular/http';
import { provideForms, disableDeprecatedForms } from '@angular/forms';
import { TranslateService, TranslateLoader, TranslateStaticLoader, MissingTranslationHandler } from 'ng2-translate';

import { CLIENT_ROUTER_PROVIDERS } from './common/routes/bootstrap.routes';
import { AppComponent } from './common/components/app.component';
import { KeyMissingTranslationHandler } from './helpers/missing-translations-handler';

bootstrap(AppComponent, [
    CLIENT_ROUTER_PROVIDERS,
    HTTP_PROVIDERS,
    disableDeprecatedForms(),
    provideForms(),
    provide(TranslateLoader, {
        useFactory: (http: Http) => new TranslateStaticLoader(http, '../assets/i18n', '.json'),
        deps: [Http]
    }),
    provide(MissingTranslationHandler, { useClass: KeyMissingTranslationHandler }),
    TranslateService
]);`

++
The NG2_UI_AUTH_PROVIDERS is my login.component.ts

**Comment by ronzeidman** [comment]
Try moving it to the bootstrap instead since you want it available in the DashboardComponent and I guess the DashboardComponent is not a child of LoginComponent

**Comment by ronzeidman** [comment]
In addition you will probably also to use JwtHttp in your entire app.

**Comment by BansheeHood** [comment]
Ahhh thanks, moving NG2_UI_AUTH_PROVIDERS to the bootstrap component works !
