### ISSUE TITLE
Google Auth Popup Window does not close

### ISSUE THREAD

**Issue by chad-autry** [ronzeidman/ng2-ui-auth#5]
The popup window does not close for me after successful authorization.
The token response is received, and the user is authorized.

No errors seen in the console.

I know we build differently, was wondering if the popup auto-closed for you like it should.
You can see my app here http://chad-autry.github.io/ng2bp I will continue to investigate.

**Comment by chad-autry** [comment]
The problem is simply in popup.ts poollPopup() this.popupWindow.close(); is commented out.

Reverting that solves the problem and lets the window auto-close. I'm guessing you were debugging something and wanted the window to stick around. I'll get a pull request out later today.

**Comment by ronzeidman** [comment]
-_- off with a bad start... I've fixed it...
I was testing something and accidentally committed (several days ago) the popup.ts:125 line commented out... fixed it.
