### ISSUE TITLE
Unable to overwrite default vars in Customconfig

### ISSUE THREAD

**Issue by marcelgoya** [ronzeidman/ng2-ui-auth#54]
I'm trying to overwrite loginUrl var in the CustomConfig object with no success. I've followed the example in the demo app but it's not working. Below my code:

```
export class MyAuthConfig extends CustomConfig {
  loginUrl: 'https://aaaaaaa';
}
```
Any help would be appreciated.

Thanks

**Comment by ronzeidman** [comment]
Try replacing the : with a =
```
export class MyAuthConfig extends CustomConfig {
  loginUrl = 'https://aaaaaaa';
}
```

**Comment by ronzeidman** [comment]
did it work?

**Comment by ronzeidman** [comment]
Closing due to no update.

**Comment by marcelgoya** [comment]
@ronzeidman Sorry about the late reply. Yes, it worked like a charm. Thx for helping me out :)
