### ISSUE TITLE
Can I call my custom OAuth2 providers?

### ISSUE THREAD

**Issue by zeroguru** [ronzeidman/ng2-ui-auth#56]
Hi at all,

first sorry for this thread but I'm new in Angular 2.

I had with satellizer the below configuration:

```
$authProvider.oauth2({
        name: 'manual',
        url: '/oauth/token',
        responseType: 'code',
        responseParams: {
            data: {
                access_token: 'access_token',
                refresh_token: 'refresh_token',
                expires_in: 'expires_in',
                roles: 'roles'
            }
        }
    });
    $authProvider.loginUrl = PROVIDER.host + '/uaa/oauth/token';
    $authProvider.tokenName = 'access_token';
    $authProvider.authHeader = 'Authorization';
    $authProvider.authToken = 'Bearer';

```

Your work was great with this porting but I didn't understand how I could call my custom OAuth2 implementation.

Thanks in advance,
Massimiliano

**Comment by mackelito** [comment]
I´m having similar questions.. did you solve it?

**Comment by Hesesses** [comment]
same problem here

**Comment by ronzeidman** [comment]
In your auth config class you can add any custom provider you like in the "providers" field, same parameters as satellizer (you have typescript auto-complete to help you).
