### ISSUE TITLE
How to specify the scope

### ISSUE THREAD

**Issue by speedfl** [ronzeidman/ng2-ui-auth#59]
Hello.
Just a question. Is there a way to specify easily the scope for the facebook access.
Here from what I can see in the code we have scope email and public profile.
Can we specify more by overriding something like friend list photos etc ? 
Thanks for your project. I was fastly able to implement connection to facebook LinkedIn  :)

**Comment by ronzeidman** [comment]
I'm glad you enjoy my lib :)
As you can see here https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/config.service.ts#L143 this is the default scope, you can override it like you override the clientId:
```ts
export class MyAuthConfig extends CustomConfig {
    defaultHeaders = {'Content-Type': 'application/json'};
    providers = {facebook: {clientId: FACEBOOK_CLIENT_ID, scope: ['email', 'user_friends', ...]}};
}
```
facebook scope options can be found here: https://developers.facebook.com/docs/facebook-login/permissions

**Comment by speedfl** [comment]
Wonderfull as usual. There is always a way to deal with my needs :)
Like I was wondering this morning how to retrieve user information when I log in and you return it! 
So perfect and perfect again!
