### ISSUE TITLE
Should the Auth Tokens be on All Requests?

### ISSUE THREAD

**Issue by chad-autry** [ronzeidman/ng2-ui-auth#6]
The https://github.com/sahat/satellizer readme indicates it sends the auth token as a header on all HTTP requests when authorized. 

I'm not seeing that happen by default, do I need to override and provide my own Http which decorates the header?

**Comment by ronzeidman** [comment]
You are right, fixed: https://github.com/ronzeidman/ng2-ui-auth/commit/b59326cc5b28d41bf0309080433085aa957a9b48
