### ISSUE TITLE
Change full url

### ISSUE THREAD

**Issue by martinop** [ronzeidman/ng2-ui-auth#62]
How I can change the url to make the request with Twitter?

I use the URL param but just replace the path and keep the domain :( i need to make a request to other domain.

for example in the config:
twitter: { clientId: "XXXXX", redirectUri: "XXXX", url:"EXAMPLE.com" }

I get:  localhost:3000/example.com

**Comment by ronzeidman** [comment]
try changing "baseUrl" in the base config
```ts
export class MyAuthConfig extends CustomConfig {
    baseUrl = 'example.com';
    providers = {twitter: { clientId: "XXXXX", redirectUri: "XXXX", url:"/twitter" }};
}
```

**Comment by ronzeidman** [comment]
No response. closing.

**Comment by martinop** [comment]
Sorry for not responding, your answer works
