### ISSUE TITLE
Refresh token when the request fails

### ISSUE THREAD

**Issue by stochris** [ronzeidman/ng2-ui-auth#65]
When a request fails with a 401 ( user configurable maybe ? ) status, pause and / or remember all incoming failed responses and do a token refresh, after which redo all the request with a authorization header 

This solves a problem that happens due to slight time differences between the server and the client ( a few seconds ).
The token can appear valid to the client, but the token is invalid to the server.

**Comment by ronzeidman** [comment]
So what do you prefer?
1) trying to refresh the token a configurable (10 min default) amount of time before it expires?
2) failing -> refreshing -> retrying
3) both

**Comment by stochris** [comment]
I personally prefer the second approach, as it seems more hands down than checking once every 10 minutes.
If the refresh time is low, the first approach might put a lot of strain on the server.

**Comment by stochris** [comment]
Implementing this would require knowing when the token is being refreshed, and waiting for it finish before doing anything

**Comment by ronzeidman** [comment]
I meant in the first approach to lazily try as opposed to eagerly try every 10 minutes.
I say before you make a Token enabled call if the token is about to expire (as opposed to already expired) try and refresh it before the actual call.

**Comment by ronzeidman** [comment]
Anyway, I'll have to think a bit about making unnecessary duplicate calls to the refresh when calling several services one after the other.

**Comment by stochris** [comment]
I'd save the request observable in SharedService

**Comment by ronzeidman** [comment]
Please try the master branch and tell me if it works for you.
I didn't save yet the token request request so if you have many parallel requests it might try to refresh the token multiple times but for now it should do the job.
the refresh before expiration is by default set to 10 minutes and `tryTokenRefreshIfUnauthorized` is set to false by default, so if you want to test that add it to your custom config.
Update me when you finish testing the branch.

**Comment by stochris** [comment]
I'l check it in the next few days. Also, I might submit a PR to solve the problem with multiple concurrent calls ( keep the token state, valid, expired, refreshed in the `SharedService` )

**Comment by stochris** [comment]
After some trouble with how the `Config`, I checked if the jwt works. I works ok. Thanks 😄

**Comment by ronzeidman** [comment]
Version 6.0.0 is on npm
