### ISSUE TITLE
Configservice resolveToken

### ISSUE THREAD

**Issue by apreg** [ronzeidman/ng2-ui-auth#68]
I try to integrate facebook in my app with the help of ng2-ui-auth.
Here is my current config: 
```
providers = {
facebook: {authorizationEndpoint: 'https://www.facebook.com/v2.8/dialog/oauth',clientId:'422321427968640', responseType: 'token', url: 'http://localhost:8080/login/facebook'}
}
```
I get back access_token in an object so the resolveToken in config.service fails at this line:
```
 const accessToken: string | Object | null | undefined = response && response.json() &&
            (response.json().access_token || response.json().token || response.json().data);
```
If I seen correctly I can define a custom resolver so I can workaround this issue.

**Comment by ronzeidman** [comment]
can you show the exact structure of the response you receive?

**Comment by apreg** [comment]
Right now I'm at work, but later today sure I can. Anyway it is a simple object with access_token property and expire.  So this`const accessToken: string | Object | null | undefined = response && response['access_token'];` works.

**Comment by apreg** [comment]
One more comment the version of facebook api does not matter, and don't let the url in my config mislead you, it has no purpose since I'm using responseType token anyway thus it does not function az an exchange server. My final goal would be to get an access_token from the facebook server and send it to my server which can then use it for further requests towards facebook on my behalf.

**Comment by ronzeidman** [comment]
the response you should receive is an http `Response` (of the @angular/http library) this inherits Body class and have this function: https://github.com/angular/angular/blob/master/modules/%40angular/http/src/body.ts#L26 
somehow you receive the already decoded object directly. Can you tell me in what flow do you get it that way?

BTW, if you have a server, why do you use the insecure way of getting the "token" directly to the client (responseType: "token")? you can go through your server. 
One of my friends did an example with facebook and twitter for this (I didn't find the time to merge it yet) you can see here: https://github.com/MosheBiton/ng2-ui-auth-example
ui config: https://github.com/MosheBiton/ng2-ui-auth-example/blob/master/client/src/config.ts
facebook server-side function: https://github.com/MosheBiton/ng2-ui-auth-example/blob/master/server/src/auth.ts#L147
You could modify the server function in such a way that stores the token and make more requests (more than the profile one in the example) for that you may need to ask for a larger "scope" though.

**Comment by apreg** [comment]
Yeah, I don't know yet how I get the object and I've seen it wants a Response which would have a json() ofc. I guess the answer is in the popup service. 
The truth is the server is not my code but I'll try to convince the maker in another round if you also find it insecure.

**Comment by ronzeidman** [comment]
I'll look further into it when I have more time... 
maybe over the weekend or the beginning of next week. All I can say now is "It works on my machine 😄 " 
Anyway if you can pinpoint the issue better or use a different solution add a comment.

this is a good small explanation of "token" vs "code", in short, if you want the server to have access to the facebook account use "code" if you want the UI to have that access to facebook directly use "token":
http://stackoverflow.com/questions/8666316/facebook-oauth-2-0-code-and-token

**Comment by apreg** [comment]
Thanks. I've seen that SO post and also facebook has good explanation ;)
What do you think can I somehow "bend" your code to work like I described above i.e. get a token or code from facebok or other external oauth service, send it to my server which will send me back a custom token which I can save on client side and use for further requests towards my server.
I have a feeling that maybe exchangeForToken function is a point where I should hook in but I haven't got time to investigate it yet.

**Comment by ronzeidman** [comment]
That's exactly the point of the library. That's what the "exchangeForToken" does - it sends the "code" to the server for the server to get an actual token from facebook and send back to the client your server's token.
try checking out the example and play with it a bit, see how you get the data in the server-side (I can vouch for my example https://github.com/ronzeidman/ng2-ui-auth-example but I've only implemented "google" auth, this one has facebook and twitter implemented: https://github.com/MosheBiton/ng2-ui-auth-example and it should work).

**Comment by apreg** [comment]
I rewrote the server code to handle `code`. Everything's working smoothly, although with token I still get an object from `PopupService` lnr. 136 ``` return Observable.of(allParams);```. allParams is an object so setToken in shared.service lnr. 45 calls resolveToken on it and then it blows up.

**Comment by ronzeidman** [comment]
You're right, but this should happen only when the responseType is 'token' not 'code'. I'll fix this

**Comment by ronzeidman** [comment]
Please try the master branch and tell me if it works for you.
Thanks

**Comment by apreg** [comment]
It seems good. Thank you.

**Comment by ronzeidman** [comment]
Version 6.0.0 is on npm
