### ISSUE TITLE
Dynamically change header content

### ISSUE THREAD

**Issue by speedfl** [ronzeidman/ng2-ui-auth#69]
Hello,

Is there a way to dynamically change header content for authentication?
As my backend is rest api my client need to generate a random request ID to keep track and send it in header.
In case of any error my client will call a bug report sender with this request ID so I will be able to parse my log to follow what happened.

Thanks a lot for your answer

Best regards

Geoffrey

**Comment by ronzeidman** [comment]
The master branch now has ability to change the http provider - `Ng2UiAuthModule.forRoot(config, MyJwtHttp)`, just create a `MyJwtHttp` that inherits the JwtHttp, override the setHeaders function and this should fix your issue.
If you can send the request ID in the body you can add it by using `this.auth.authenticate('google', {requestID: ...})`
Please update that the master works for you so I will publish it to npm.
Thanks

**Comment by speedfl** [comment]
I will try tomorrow and let you know :)

**Comment by speedfl** [comment]
Hello.
I won't have time to test today but I won't forget :)

**Comment by ronzeidman** [comment]
You're the last one remaining before I'll publish this version.
Have you had time to verify?

**Comment by speedfl** [comment]
I am really sorry. This was a really hard working week. I will test at lunch time.
I will keep you posted

**Comment by speedfl** [comment]
Btw it is not in the body but in the header I need to send my request ID

**Comment by speedfl** [comment]
So i am not able to make it work. Maybe I did something wrong but I am getting a no provider for MYJwtHttp

`
import {Injectable} from '@angular/core';
import {Http} from '@angular/http';
import {JwtHttp, ConfigService, SharedService} from 'ng2-ui-auth';
import {HeaderUtils} from './headerUtils';

@Injectable()
export class MyJwtHttp extends JwtHttp {

  setHeaders(options){
    if(options){
      options['HY-Request-ID'] = HeaderUtils.generateRequestID()
    } else{
      options = {
        'HY-Request-ID' : HeaderUtils.generateRequestID()
      };
    }
    super.setHeaders(options);
  }
}
`

Then in the app.module.ts

`imports: [Ng2UiAuthModule.forRootWithCustomHttp(MyAuthConfig, MyJwtHttp)]`

Do you maybe have an idea?

**Comment by ronzeidman** [comment]
try this:
```ts
imports: [Ng2UiAuthModule.forRootWithCustomHttp(MyAuthConfig, {provide: JwtHttp, useClass: MyJwtHttp, deps: [Http, SharedService, ConfigService]})]
```

**Comment by speedfl** [comment]
Man how can I say...

You rocks!!!! :)
This works perfectly. Thx and sorry for the delay. I had lot of work.


So basically:

`
	    import {Injectable} from '@angular/core';
	    import {Http, Headers} from '@angular/http';
	    import {JwtHttp, ConfigService, SharedService} from 'ng2-ui-auth';
	    import {HeaderUtils} from './headerUtils';

	     @Injectable()
	    export class MyJwtHttp extends JwtHttp {

	    protected setHeaders(obj: { headers?: Headers, [index: string]: any }){
		console.log(obj);
		if(!obj){
			obj = {};
		}
		if(!obj.headers){
		  obj.headers = new Headers();
		}
		obj.headers.set('RequestID', HeaderUtils.generateRequestID());

		super.setHeaders(obj);
		console.log(obj);
	  }
	}
`

Then in app module what you said and it is working.

This will allow every people who want to inject something specific in the header to override it.

Again thanks :)

**Comment by speedfl** [comment]
:+1:

**Comment by ronzeidman** [comment]
Version 6.0.0 is on npm
