### ISSUE TITLE
ng2-ui-auth.js not found

### ISSUE THREAD

**Issue by heinbez** [ronzeidman/ng2-ui-auth#7]
Hey there,

First of all thanks for converting this library. I'm having some troubles where system.js isn't loading ng2-ui-auth.

In my login.ts I have,

```ts
import {Component, View, AfterContentInit, ElementRef, Renderer} from 'angular2/core';
import {Router, ROUTER_DIRECTIVES} from 'angular2/router';
import {FormBuilder, ControlGroup, Validators} from 'angular2/common';

import {Auth} from 'ng2-ui-auth';
```

and in my bootstrap.ts I have,

```ts
import {NG2_UI_AUTH_PROVIDERS, JwtHttp} from 'ng2-ui-auth';

bootstrap(App, [
   ...
    NG2_UI_AUTH_PROVIDERS({
    	providers: {
    		google: {
    			clientId: GOOGLE_CLIENT_ID
    		},
    		facebook: {
    			clientId: FACEBOOK_CLIENT_ID
    		}
    	}
    }),
    JwtHttp,
    ...
]);
```

It's also in my dependencies,

```json
  "dependencies": {
    "angular2": "2.0.0-beta.1",
   ...
    "systemjs": "0.19.6",
    "ng2-ui-auth": "~1.0.12"
  },
```

I'm using Typescript as my compiler. Am I suppose to somehow manually include the library in my `index.html`?

Thanks in advance,
H.

**Comment by ronzeidman** [comment]
in systemJS in the config file you can just use 
```typescript
SystemJS.config({
    defaultJSExtensions: true,
    paths: {
        './*': './*',
        '../*': '../*',
        '*': './node_modules/*'
    },
    packageConfigPaths: ['./node_modules/*/package.json'],
```
and it will load everything automatically from your node_modules folder.
you can see https://github.com/ronzeidman/open-ng2-tests for an example

**Comment by heinbez** [comment]
I'll try it out! Thanks. Angular2 is so confusing to start with.
