### ISSUE TITLE
Issue with rxjs ~5.0.3?  

### ISSUE THREAD

**Issue by BeanoKing** [ronzeidman/ng2-ui-auth#74]
After moving to this rxjs version in my project my authenticate(provider).subscribe is blowing up.  I noticed this package uses beta-12.  Do you know if this would be causing the problem I'm seeing?  Also, is there a workaround until this package is updated to use the latest rxjs?  

Thanks

**Comment by BeanoKing** [comment]
I reverted back to Angular 2.0.1 and rxjs beta 12 and all is well.  I'll use that as the workaround for now.

**Comment by ronzeidman** [comment]
I'm using beta 12 to comply with any angular 2.X.x but I guess that's not working anymore. I'll upgrade my projects and look into it further. 
Thanks

**Comment by ronzeidman** [comment]
I've just tested it in my system and it works without any changes (angular 2.4.3, rxjs 5.0.3, ng2-ui-auth 6.0.0. webpack 2.1.0-beta.28) can you give me the exact error call stack?

**Comment by BeanoKing** [comment]
Interesting.  I'm not able to get a good error.  The console says the call stack is too large to display, but it's something in rxjs itself.  How are you making the authentication(provider) call?  I may be using an old school way that isn't supported anymore.  

My code to make the authentication call:  

```javascript
      this._oauth.authenticate(provider)
        .subscribe(
            (response: Response) => context._handleLoginResponse(response.json()));
```

**Comment by ronzeidman** [comment]
Yes,
```ts
this.auth.authenticate(provider).subscribe(....)
```
does it happen as soon as you subscribe?
Can you try using the subscription error handler:
```ts
this._oauth.authenticate(provider)
    .subscribe(
        (response: Response) => context._handleLoginResponse(response.json()),
        (error: any) => console.log(`Error through handler: ${error.toString()}`)
     )
```

**Comment by BeanoKing** [comment]
It won't even go to the error handler, so I don't know what the deal is.  Thanks for trying to help but it seems to be something wrong my setup.  I'm closing this issue.
