### ISSUE TITLE
Option to change the default POST method

### ISSUE THREAD

**Issue by lafama** [ronzeidman/ng2-ui-auth#77]
Is it possible to have an option to change the default **POST** that occurs after a successful login to a **PATCH** or **PUT** request instead

Example : ``google:{clientId: 'xxxxx.apps.googleusercontent.com',url:'http:/localhost:9000/shop/auth/google',method:'PATCH'}``

**Comment by ronzeidman** [comment]
Seems like a small enough fix. Do you want to create a pull request? If not, I will look into it Sunday.

**Comment by ronzeidman** [comment]
Do you mean the "exchangeForToken" call? the one who sends the temporary token to your server in order to generate your own token?

**Comment by lafama** [comment]
I thinks that's the correct one. Does it make use of the URL parameter?

**Comment by ronzeidman** [comment]
yes

**Comment by ronzeidman** [comment]
Please test the master branch

**Comment by lafama** [comment]
Works perfectly. Thank you
