### ISSUE TITLE
Support for defaultUrlParams customization

### ISSUE THREAD

**Issue by loganmzz** [ronzeidman/ng2-ui-auth#79]
It is currently not possible to have custom *UrlParams because merge functions transform "conflicting arrays" into objects which have no "forEach" support. It causes an exception in `Oauth2Service.buildQueryString()` when trying to iterate over `this.defaults[params]`

**Comment by ronzeidman** [comment]
Can you give an example input? and where exactly it fails?

**Comment by loganmzz** [comment]
I have used "defaultUrlParams" instead of "optionalUrlParams"

**Comment by ronzeidman** [comment]
So is there still an issue?

**Comment by loganmzz** [comment]
Bug occurs on "defaultUrlParams". I update the title but let you decide if not customizing "defaultUrlParams" is bug or not.

**Comment by ronzeidman** [comment]
removed ability to change defaultUrlParams in version 7.0.1
