### ISSUE TITLE
ng2-ui-auth.js not found

### ISSUE THREAD

**Issue by heinbez** [ronzeidman/ng2-ui-auth#8]
Hey there,

First of all thanks for converting this library. 

## Update

I'm now getting the error `http://10.0.0.135:3000/rxjs.js 404 (Not Found) system.src...` when including the library like so:

```js
System.config({
	packages: {
		app: {
			defaultExtension: 'js'
		},
		'node_modules': {
			defaultExtension: 'js'
		}
	},
	map: {
		'angular2-jwt': 'node_modules/angular2-jwt/angular2-jwt.js',
		'ng2-ui-auth': 'node_modules/ng2-ui-auth/export.js',
	}
});
```

I already do have rx included 

```
<script src="/node_modules/rxjs/bundles/Rx.js"></script>
```

And I only get the error when including `ng2-ui-auth`

**Comment by ronzeidman** [comment]
in systemJS in the config file you can just use

SystemJS.config({
    defaultJSExtensions: true,
    paths: {
        './*': './*',
        '../*': '../*',
        '*': './node_modules/*'
    },
    packageConfigPaths: ['./node_modules/*/package.json'],
and it will load everything automatically from your node_modules folder.
you can see https://github.com/ronzeidman/open-ng2-tests for an example
