### ISSUE TITLE
Not able to make it work with ionic2

### ISSUE THREAD

**Issue by navneet35371** [ronzeidman/ng2-ui-auth#80]
the request.body in my express server is an empty object. I am using the latest version with config as
`
export class MyAuthConfig extends CustomConfig {
    defaultHeaders = {'Content-Type': 'application/json'};
    providers = {
      google: { clientId: CONFIG.GOOGLE_CLIENT_ID },
      facebook: { clientId: CONFIG.FACEBOOK_KEY }
    };
    tokenName = 'accessToken';
    tokenPrefix = '';
    baseUrl = CONFIG.API_ENDPOINT;
}
`

**Comment by royipressburger** [comment]
Can you attach an example of a  request you are making?

**Comment by ronzeidman** [comment]
Closing, no response
