### ISSUE TITLE
Safari Private Browsing

### ISSUE THREAD

**Issue by simkepal** [ronzeidman/ng2-ui-auth#81]
Hello,

I have a problem with login in private browsing. Everything works ok but it can not save the token in localStorage. So user is logged out after navigating to another link. It would be great to somehow degrade to cookies if localStorage is not awailable. Is this possible?

Thank you for your help!

**Comment by ronzeidman** [comment]
Nice recommendation. It is pretty easy to implement. You can add two options to the config - storageType cookie and a degradeToCookie option. Then add the logic to store the token as a cookie to the Storage class.
This month I don't have much time so I'd appreciate a pull request. If you don't it may take a small while until I implement it myself.

**Comment by simkepal** [comment]
I also don't have much time at the moment. I will try to do this as soon as possible... If you don't do it first...

**Comment by Hesesses** [comment]
any news about this?

**Comment by ronzeidman** [comment]
It should be pretty easy to implement `document.cookie = ...` instead of `localStorage.setItem(...)` if certain config parameters are set. If you need it you are welcome to submit a pull request, I'd be happy to merge it.

**Comment by ronzeidman** [comment]
now supporting 'cookie' and 'sessionCookie' as storage methods in version 7.0.1

**Comment by CGTAbhay** [comment]
How can i overwrite the storageType:'cookie' in CustomConfig
