### ISSUE TITLE
Warning and version update

### ISSUE THREAD

**Issue by lafama** [ronzeidman/ng2-ui-auth#85]
Using Angular 4.0

``npm WARN ng2-ui-auth@6.1.3 requires a peer of @angular/http@^2.0.0 but none was installed.
npm WARN ng2-ui-auth@6.1.3 requires a peer of @angular/core@^2.0.0 but none was installed
``
Can we also have a release version with the latest changes instead of referencing master

**Comment by ronzeidman** [comment]
Done (version 6.1.4)
