### ISSUE TITLE
How to ask for credentials every time in popup window?

### ISSUE THREAD

**Issue by robgaleano** [ronzeidman/ng2-ui-auth#86]
It doesn't seem very clear on documentation, or at least i don't know if this is a current feature, but if it exists can someone please tell me how to implement it? i've been using the library for a while and it works perfect but i need it to ask for credentials every time the popup appears instead of just being loaded automatically from cookies or from whatever the last session on the social network is stored.

**Comment by ronzeidman** [comment]
Hi, every provider has his own implementation for such a feature.
Google for example has an additional optional "prompt" parameter which you can use to force users to go to the "select account" screen or "consent" screen.
```ts
    providers = {google: {
        clientId: GOOGLE_CLIENT_ID,
        prompt: 'select_account'
    }};
```
https://developers.google.com/identity/protocols/OAuth2UserAgent

Other providers may have different parameters or maybe they don't support such an option at all.

**Comment by ronzeidman** [comment]
No response, closing.
