### ISSUE TITLE
Ionic 2.2.0 CORS issue.

### ISSUE THREAD

**Issue by andrebouchard** [ronzeidman/ng2-ui-auth#87]
After updating a current project to Ionic 2.2.0, ng2-ui-auth suddenly stop working properly; im always receiving a CORS errors on Android devicen from a login call. The app still work fine in ionic LiveReload (using the Allow-Control-Allow-Origin chrome plugin). ng2-ui-auth 6.0.0 was the first thing implemented in the projects months ago and worked fine until the update to 2.2.0.

I also tested the 6.1.0 release but same results. Nothing was changed in the code of the project itself, only libs in node_modules were updated in the process. The update itself went without errors or warning (missing dependencies, etc).

Does ng2-ui-auth have been tested on the latest Ionic platform? Is it a known issue?

Thank you for any input you may have.

**Comment by royipressburger** [comment]
Im using it with ionic 2.3 with no problem.. can you share some code and the full error you are getting?

**Comment by andrebouchard** [comment]
Its a simple call to a server where the url is defined in a route variable and the credentials JSON object is passed as post params. Been working fine for the last 3 months.

`this.jwtHttp.post(this.route, this.formatData(data)).map(res => <Token>res.json());`

The full error is a straight forward basic CORS error:

` {"isTrusted:"true"}`

By the way, to update to 2.3 do you only have to set "ionic-angular" to "2.3.0" in package.json and re-install via npm? I could not find a procedure for upgrading to 2.3.

**Comment by royipressburger** [comment]
@andrebouchard  really hard to tell like this. You didn't change anything in the server? What headers are being sent in the request?
I doubt that this is ionic problem, but just in case add `ionic info`

updating to ionic 2.3 is just installing "ionic-angular"

**Comment by andrebouchard** [comment]
Thanks, updated to 2.3. Alas the problem persist.

Also, yes, nothing changed on the server. Plus, login request to the server in LiveReload still work like usual.

Here is my info: 

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by andrebouchard** [comment]
I was able to make it work in a fresh new Ionic 2.3.0 projects. Ill come back and close this issue when i finished my test and fixed the problems. Its clear its has nothing to do with a compatibility between the plugin and Ionic 2.3.0

**Comment by andrebouchard** [comment]
My problem is fixed. The plugin do work with ionic 2.2.0, ionic 2.3.0 and ionic 3 (beta).
