### ISSUE TITLE
Google login problem

### ISSUE THREAD

**Issue by diegodfsd** [ronzeidman/ng2-ui-auth#88]
I can't login with my google account and I think the new google login screen it is a problem. Someone else is having problem?

**Comment by ronzeidman** [comment]
I'm having error 500... Error 500 is an internal server error so it should be Google's fault but it's Google right?
I'm looking into it. What do you mean new google login screen?

**Comment by ronzeidman** [comment]
Workaround: use `optionalUrlParams: ['display', 'state']` in the providers field on your auth config class

**Comment by ronzeidman** [comment]
Fixed: try using version 6.1.5, report that the bug is fixed and close this issue.

Thanks!

**Comment by diegodfsd** [comment]
After I can see your suggestion I compare the URL and found that hd
parameter was a reason. I will update your version as soon as possible.

Thank you.

**Comment by diegodfsd** [comment]
I mean before I can check you suggestion I  identified that empty parameter hd was the reason behind error and I override the optional parameters and now everything works fine.

Thank you
