### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by mmteyrek** [ronzeidman/ng2-ui-auth#89]
Hello,
First, thank you for your effort to upgrade satellizer.
I start using your library today, for the login it's working very well.
But for logout, the token remains in the session local storage.
I'm using these commands to log out : 
   		this.auth.removeToken;
   		this.auth.logout;

Thank you in advance.

**Comment by ronzeidman** [comment]
Hi,
Both work for me. have you changed any related configuration (tokenName, tokenPrefix, tokenSeperator)?
Can you show me your config file so I can replicate the issue?

**Comment by mmteyrek** [comment]
Hello,
finaly I looked to your example :+1: 

    logout() {
        this.auth.logout()
            .subscribe({
                error: (err: any) => console.log(err),
                complete: () => this.router.navigateByUrl('login')
            });
    }

with the subscribe, it's working well (don't know why :)).
