### ISSUE TITLE
OAuth2 logins (FB and Google) flakey?

### ISSUE THREAD

**Issue by ProximitorErin** [ronzeidman/ng2-ui-auth#90]
If the Observable interval in the pollPopup() method of popup.service.ts is left at 50, it seems like the popup window's location frequently gets chopped, resulting in incomplete parameters being passed - like a missing "code".  Setting this down to 5 seems to resolve the issue.  Clearly, it is working for many people, so may be specific to some OS/hardware combinations.  I've seen this behavior on both Chrome and Safari, but only been able to test on a 2.6 GHz Intel Core i7 macOS Sierra machine.

**Comment by ronzeidman** [comment]
Very weird issue. Can you give me example settings that it happens on or using the default settings (and only adding public key) causes this issue at your machine?

**Comment by ProximitorErin** [comment]
Just default settings...

providers = {google: {clientId: GOOGLE_CLIENT_ID},
                facebook: {clientId: FACEBOOK_CLIENT_ID} };

The call is equally straightforward...

this.auth.authenticate('facebook')
      .subscribe({
        error: (err: any) => this.printEm(err),
        complete: () => this._router.navigate(['home'])
    });

In a "bad run", queryParams comes back blank and hashParams is just _ 
In a "good run", queryParams looks like _=_ and hashParams is code=  and then whatever the returned code should be.

**Comment by richardjprice** [comment]
I think we're seeing this issue in our code with a google oauth implementation, but we haven't been able to isolate exactly what is causing the intermittent issue.

**Comment by ProximitorErin** [comment]
I'd be interested to know - if you set that value to 5 instead of 50, does the issue go away for you?  I does for me.  Also - as another data point - if you set it to 500 (order of magnitude in the other direction), for me - that makes it break every single time instead of just intermittent.  So - actually, that's a good way to repro the issue, now that I think about it... must be something about 50 being fast enough to capture some browsers' implementations on some machines state changes, but not on others.

**Comment by richardjprice** [comment]
We have done as ProximitorErin mentioned, and when the setInterval is 5, we didnt experience any issues. 

When we set the interval to 500, it was failing everywhere. 

It was an intermittent issue but we had some users experience the issue more often than others, when set at 5, even these users were authenticating correctly.

**Comment by ronzeidman** [comment]
Thanks for reporting. I'll update the code soon

**Comment by ProximitorErin** [comment]
Thanks!

**Comment by ronzeidman** [comment]
Hmm... I was looking more thoroughly on the code and on how to create a reproduction scenario on my end. I see this can only happen if directly after the redirection your code (the client's router) does anther redirection and that is not caught.

The logic of this library goes as follows:

- Open popup to the oAuth provider with the configured params
- When the popup redirects to your site: (this is the interval and where your code goes wrong)
  - close the popup
  - parse the parameters that the popup had and send them to the server in order to exchange them with your token
- get the token from your server and save in the local storage

Seems that what went wrong is that when google/facebook redirects back to your site somehow your router causes anther redirect which truncates the parameters that were sent by them. Can you look into it? try entering your redirection address manually and see if it gets redirected?

**Comment by ProximitorErin** [comment]
Interesting... I'll check it out and let you know!

**Comment by netopolit** [comment]
I can reproduce on both Safari and Edge. Any news on this?
Thanks.

**Comment by ronzeidman** [comment]
This seems like a local issue of your site. If your site clears parameters or redirects from the redirect page this could happen.
You should verify that the redirect route does not change the url automatically. This library waits for the redirection in the popup window and captures the variables from the url, if they change it won't be able to read them. If I change the interval to 5ms than I'm wasting cpu cycles/battary power..

**Comment by ronzeidman** [comment]
For everyone having the same issue, the easiest way is to create an endpoint of a blank page in your app (`/api/blank`) and set the redirect there.

**Comment by ProximitorErin** [comment]
So, you mean - for example - create an /api/blank endpoint in my Angular application and tell Facebook/Google that my app's URL is (for example) http://localhost:3000/api/blank instead of just http://localhost:3000?

**Comment by ronzeidman** [comment]
@ProximitorErin exactly, but make sure /api/blank is not a part of your angular app (doesn't return index.html) but instead just returns a blank page.

**Comment by ProximitorErin** [comment]
Alright - I'll give it a shot.  Thanks!
