### ISSUE TITLE
Satellizer for angular2 

### ISSUE THREAD

**Issue by tomNjerry** [ronzeidman/ng2-ui-auth#92]
How to set up the end point url to our server for authenticating and generate  the jwt  token 

Please help

**Comment by ronzeidman** [comment]
You can add `baseUrl` to the configuration class you send the module

**Comment by tomNjerry** [comment]
can i get the demo i.e example showing to config 2 provider with baseUrl in config.ts 
please help

**Comment by tomNjerry** [comment]
the base URL is not working

**Comment by ronzeidman** [comment]
Can you show me the config class you are using?
should look like this
```ts
export class MyAuthConfig extends CustomConfig {
    defaultHeaders = {'Content-Type': 'application/json'};
    providers = {google: {clientId: GOOGLE_CLIENT_ID}};
    baseUrl = '/'; //your server's base url
    loginUrl = '/auth/login'; //login endpoint (will be added after the baseUrl)
    signupUrl = '/auth/signup'; //signup endpoint (will be added after the baseUrl)
    unlinkUrl = '/auth/unlink'; //unlink endpoint (will be added after the baseUrl)
    refreshUrl = '/auth/refresh'; //refresh endpoint (will be added after the baseUrl)
}
```

**Comment by tomNjerry** [comment]
import {CustomConfig} from 'ng2-ui-auth';
import {Router} from '@angular/router';

export const FACEBOOK_CLIENT_ID = '187935578305710';

export class MyAuthConfig extends CustomConfig {
   private route: Router;
    defaultHeaders = {'Content-Type': 'application/x-www-form-urlencoded'};
    providers = {facebook: {clientId: FACEBOOK_CLIENT_ID,redirectUri: }};
    baseUrl = 'https://www.friendcolony.com/FC_API/index.php/User_Rest_Api/facebook';
}

**Comment by tomNjerry** [comment]
If any correction Required then please guide the same

**Comment by ronzeidman** [comment]
```ts
import {CustomConfig} from 'ng2-ui-auth';
import {Router} from '';

export const FACEBOOK_CLIENT_ID = '187935578305710';

export class MyAuthConfig extends CustomConfig {
private route: Router;
defaultHeaders = {'Content-Type': 'application/x-www-form-urlencoded'};
providers = {
     facebook: {
        clientId: FACEBOOK_CLIENT_ID,
        url: '/facebook' //this is an addition specific for the provider
     }
};
baseUrl = 'https://www.friendcolony.com/FC_API/index.php/User_Rest_Api'; //this is the base Url
}
```
Should fix it for you

**Comment by tomNjerry** [comment]
thank you

**Comment by tomNjerry** [comment]
It's giving me problem refer the screenshot 
![capture-satellizer](https://cloud.githubusercontent.com/assets/17373795/26292140/31135a4a-3ed1-11e7-93fb-e7db2f1c9771.JPG)

how to give the redirect-url

**Comment by ronzeidman** [comment]
Maybe there is some issues with the cookies you have, try doing this in incognito mode

**Comment by ronzeidman** [comment]
These looks like the same issue: 
https://github.com/sahat/satellizer/issues/742
https://github.com/magus/react-native-facebook-login/issues/48
https://github.com/nraboy/ng-cordova-oauth/issues/186
https://stackoverflow.com/questions/31879804/you-are-not-logged-in-please-log-in-and-try-again

From a quick read it seems like a settings configuration issue with valid callback urls

**Comment by pootzko** [comment]
Did something change about this? `CustomConfig` doesn't seem to be a part of `ng2-ui-auth` anymore.

Thnx

**Comment by pootzko** [comment]
Ok, this obviously works:

```ts
Ng2UiAuthModule.forRoot(new AuthConfig())
```

Is this the recommended way to do it now or is there a different "default" approach you had in mind?
