### ISSUE TITLE
Twitter login is not working, the popup shows nothing

### ISSUE THREAD

**Issue by revanthmahesh** [ronzeidman/ng2-ui-auth#96]

**Comment by ronzeidman** [comment]
https://github.com/MosheBiton/ng2-ui-auth-example
this is an old fork of my example project where twitter seems to be working. if there were any changes in the twitter oauth api since then I'll be happy to update my library.

**Comment by revanthmahesh** [comment]
i need have a server application to access twitter login?  we could avoid that in other social platforms

**Comment by ronzeidman** [comment]
Since Twitter uses oauth 1 and not 2 it doesn't have the "token" option like 2 has so I don't think you can avoid having a server in Twitter

**Comment by pcdummy** [comment]
Twitter login works fine here: 

https://ng2-satellizer.pc-dummy.net/home
