### ISSUE TITLE
the ACCESS token is not stored in Local storage , so cant fetch details using payload function, is Authenticated function is also not getting called 

### ISSUE THREAD

**Issue by revanthmahesh** [ronzeidman/ng2-ui-auth#97]

**Comment by ronzeidman** [comment]
You get the access token in the server-side, if you want to send it also to the client you can.

**Comment by revanthmahesh** [comment]
as in storage service ts file, the token need to be stored in local storage, which later called in payload function and is Authenticated function

**Comment by ronzeidman** [comment]
The access token (to your server, I thought you meant to the provider server) is stored in the local storage:
https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/oauth.service.ts#L31

**Comment by ronzeidman** [comment]
Can you explain the full scenario? I haven't been able to reproduce the issue.

**Comment by revanthmahesh** [comment]
you can close this issue
