### ISSUE TITLE
responseType = 'token' not returning control to client app

### ISSUE THREAD

**Issue by tdekoekkoek** [ronzeidman/ng2-ui-auth#98]
I've set responseType='token' as per the satellizer docs as I need to process the result from the client app.  It gets to this point in oauth.service, but once in the .switchMap function the popup closes and control is never returned to any part of the app. 

        return openPopup
            .switchMap(function (oauthData) {
            if (!options.exchangeForToken && (_this.defaults.responseType === 'token' || !_this.defaults.url)) {
                return Observable_1.Observable.of(oauthData);
            }
            if (oauthData.state && oauthData.state !== _this.storage.get(stateName)) {
                throw 'OAuth "state" mismatch';
            }
            var exchangeForToken = options.exchangeForToken;
            if (typeof exchangeForToken !== 'function') {
                exchangeForToken = _this.exchangeForToken.bind(_this);
            }
            return exchangeForToken(oauthData, userData);
        });

**Comment by ronzeidman** [comment]
Try using the master branch `npm i ronzeidman/ng2-ui-auth`

**Comment by tdekoekkoek** [comment]
thanks.  will check it out.

**Comment by ronzeidman** [comment]
fixed in version 7.0.1
