### ISSUE TITLE
Google Login not working on Firefox for Android

### ISSUE THREAD

**Issue by pcdummy** [ronzeidman/ng2-ui-auth#99]
Hi,

I work on a fork of your example with a **Go** Server and the original layout of **satellizer**, see: https://ng2-satellizer.pc-dummy.net - I'll publish it once its polished.

Signup, Login and "Sign in via Google" works on Firefox on Linux, Chrome on Android, Chromium on Linux but **NOT with Firefox on Android**.

ng2-ui-auth opens a second tab on "Firefox for Android" the login process on Google starts but then it doesn't redirect to "/auth/google" or "/api/auth/v1/a/google" in my case.

Thanks,
René Jochum

**Comment by ronzeidman** [comment]
Interesting, I'll look into it.

**Comment by pcdummy** [comment]
As a a note - on the default Android 6.0.1 Browser i just get "Authentication Canceled".

**Comment by ronzeidman** [comment]
@pcdummy seems like it's an automatic popup blocker. Most popup blockers don't block popups originating from a click event. Maybe on mobile we should use an iframe instead.

**Comment by julienR2** [comment]
I bumped into this error to while using the Responsive Mode of Firefox (Nightly version).
Could be an easier way to reproduce and debug this issue !

**Comment by ronzeidman** [comment]
Can someone confirm this is still an issue with version 8.0.0? `npm i ng2-ui-auth@8.0.0-beta.2`

**Comment by pcdummy** [comment]
Works with 8.0.1, will close this issue.

**Comment by lafama** [comment]
I believe this is still an issue with chrome on the Iphone. Any work around ?

**Comment by epot** [comment]
It seems I have the issue with Chrome on Android on my side :(.
